### ISSUE TITLE
Increase font size for whole application

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1000]
Related to #995 (topic 1).

Make font size bigger (14pt) across the whole app - homepage, search, examine screens. 

Handle any layout issues that arise from that, such as button placement.

Acceptance Criteria:
- font for entire app is larger than it was
- when an examiner increases the size via their browser zoom, the font increases even more.

**Comment by perkinss** [comment]
Yay! I'm an assignee!

**Comment by katiemcgoff** [comment]
@JohnamLane  ready for review in DEV.

**Comment by JohnamLane** [comment]
@katiemcgoff 
Please move to Test for review by examiners.
