### ISSUE TITLE
more keyboard shortcuts

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1001]
##### _**Detailed Description**_
Please add the following keyboard shortcuts:

**Examine Names**
Show details - Alt-B
Hide Details - Alt-B 

**Decision**
Cancel - change label to "Back", Alt-C
Reject - Alt-R
Approve - Alt-A

**Comment by JohnamLane** [comment]
@perkinss Let me know if you have any questions on this one.

**Comment by katiemcgoff** [comment]
@JohnamLane ready for review in DEV.

**Comment by JohnamLane** [comment]
@katiemcgoff please move to test

**Comment by JohnamLane** [comment]
@katiemcgoff please move to prod.
