### ISSUE TITLE
Shrink the NR details banner

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1002]
##### _**Detailed Description**_
Names Examiners would like the NWPTA fields hidden from the minimized view of the NR details banner, unless it is the version in which the client has requested NWPTA #s.

With these fields out of the way, there is room to slide the bottom of the banner upward until the edit button is just below the status label. This should leave room for Jurisdiction and AB/SK requested below the request type. See image for more details. Let me know if this doesn't make sense.

![image.png](https://images.zenhubusercontent.com/5a7391bd4b5806bc2bc54a79/d1dc19ea-e13e-4d38-8ed1-0a3a553519b3)

**Comment by katiemcgoff** [comment]
@JohnamLane  ready for review in DEV.

**Comment by JohnamLane** [comment]
@katiemcgoff Please move to test

**Comment by JohnamLane** [comment]
@katiemcgoff ready for production
