### ISSUE TITLE
Tab from manual search to top of Conflicts list

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1005]
Examiners want to be able to tab straight from manual search to first conflict in list.

Acceptance criteria:
- when cursor is in manual search text field and they click tab AND there are conflicts, they are now focused on the first conflict list.
- when cursor is in manual search text field and they click tab AND there are no conflicts, focus is on the empty conflicts list. @JohnamLane FYI we don't do anything special when there are no conflicts.

**Comment by katiemcgoff** [comment]
@JohnamLane ready for review in DEV.

**Comment by JohnamLane** [comment]
@katiemcgoff Please move to Test.

**Comment by JohnamLane** [comment]
@katiemcgoff ready to move to prod.
