### ISSUE TITLE
Examination recipe changes

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1006]
Examination recipe changes per examiner feedback: 

- make cols 3 and 4 narrower
- make arrows narrower
- conflicts and history list wider
- font inside lists bigger
- vertical padding of options in lists bigger (start w. 5px and review w. @JohnamLane )

Acceptance criteria (vague):
- examiners can read conflict and history lists better
- examiners can still read columns 3 and 4 (conflict/history info + this request info side by side)

**Comment by katiemcgoff** [comment]
@JohnamLane  ready for review in DEV.

**Comment by JohnamLane** [comment]
@katiemcgoff 
Please move to Test for review with examiners.

**Comment by JohnamLane** [comment]
@katiemcgoff Ready to move to prod.
