### ISSUE TITLE
Edit Names Request

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#101]
[Information About NRO Applicant and other contacts.docx](https://github.com/bcgov/name-examination/files/1872905/Information.About.NRO.Applicant.and.other.contacts.docx)
#### **Story**
As an examiner I want to be able to edit small issues withe the submission data so that I can continue with the examination and the client does not have to do a re-submission. THIS DOES NOT INCLUDE NWTPA.  THAT IS A SEPARATE STORY.

##### BDD Pseudo-Code (GIVEN "context" ... AND "more context" ... WHEN "this action occurs" ... THEN ..."result")
GIVEN the NR is the current one the examiner is working on and it has a status="IN PROGRESS" 
WHEN the Name Request Details have changed and the Save button has been clicked
THEN allow the NR details to be updated in the database.

##### _**Acceptance Criteria**_
-Allow the user to edit the following NR fields: 
- All 3 name choices
- Request Type (e.g. Corporation - Incorporation/Amalgamation)
- Applicant Information:
      -Applicant First and Last Name
      -Applicant Address
      -Application Email Address
      -Contact Person Name 	 
      -Contact Person Phone Number	  
      -Contact Person Fax Number 
- Jurisdiction
- Nature of Business (this must be read-only)
- Additional Information (this must be read-only)
-expiry date is editable where status=Approved and consumption_date=NULL
-Includes a Save button  in the UI to trigger the save.

##### _**Issue Checklist**_
- [x] BDD Pseudo-Code 
- [x] Estimate  
- [x] Priority Label  
- [x] Story Label  
- [x] Assignee 
- [x] Linked EPIC  

##### _**Definition of Done**_
- [x] Analysis/Design 
- [ ] DB 
- [ ] UI 
- [ ] Integration Points
- [ ] Logic
- [ ] Test Script

**Comment by JohnamLane** [comment]
Here is the list of valid request types formatted as a select box.

[request types.txt](https://github.com/bcgov/name-examination/files/1905217/request.types.txt)

**Comment by JohnamLane** [comment]
Business Rules complete under #409
Document is here:
[https://app.zenhub.com/files/118046288/c5cd3729-531e-4184-9296-6b49ddbccf35/download](https://app.zenhub.com/files/118046288/c5cd3729-531e-4184-9296-6b49ddbccf35/download)
