### ISSUE TITLE
Related Corp# missing in namex

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1013]
##### _**Detailed Description**_
New BC Corporation - Change of Name submitted via NRO (public role) is missing the related corp # field in Namex. I supplied BC0769384, and this shows in the additional info, but not in related corp.

Example NR in Test: NR 9296543

**Comment by katiemcgoff** [comment]
@JohnamLane ready for your review in TEST. This is a change to the extractor, so will only affect new NRs that you create in NRO (test).

**Comment by JohnamLane** [comment]
@katiemcgoff Ready for prod.
Verified with  NR 9623104
