### ISSUE TITLE
Cant Find Restricted Words with solr operators around them

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1023]
##### _**Detailed Description**_
+REDROYAL CARPET CLEANING SERVICES  - should result in finding ROYAL as a restricted word.  I believe there are two issues:  SOLR synatx (+, ", - @ ). does not find the embedded restricted word

REDROYAL CARPET CLEANING SERVICES -  should result in ROYAL as a restricted word but again doesnt find it.

This use to work so something was changed.
##### _**Acceptance Criteria**_

Find any restricted word as a whole word or embedded inside any word within a name choice.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by kialj876** [comment]
@JohnamLane this is ready to test in dev!

**Comment by JohnamLane** [comment]
@kialj876 Ready to move to test.

**Comment by JohnamLane** [comment]
@kialj876 Please roll back the code that searches for embedded words, but keep the part that strips the Solr operators.

**Comment by kialj876** [comment]
@JohnamLane ready to test in dev

**Comment by JohnamLane** [comment]
@kialj876 Ready to move to Test.
+@-"DOCTOR" finds doctor 
DOCTORIT does not

**Comment by katiemcgoff** [comment]
@kialj876 @JohnamLane What is the status us this? Ready for deployment to production tonight?

**Comment by LJTrent** [comment]
@katiemcgoff @JohnamLane @kialj876   I have tested this in TEST and it is working.  I have moved it to PROMOTE TO PROD.
