### ISSUE TITLE
UI - BC Gov heading improvements

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1029]
Goal:  Follow BC Gov standards. 

Blue background of heading should be #003366
Remove "Logout" button style

Load button border and roll over to be  #1a5a96  

Login/Logout to follow standards - move to the right of the screen 

See here for screenshot examples of Login button and logged in state:
https://www2.gov.bc.ca/gov/content/governments/services-for-government/information-management-technology/identity-and-authentication-services/login-best-practices/government-website-headers 

.RequestInfoHeader (and all text in header) to be at least 14px

**Comment by katiemcgoff** [comment]
@juliainkster Please review changes. Especially around search bar position and button:

![2018-10-18_12-16-10](https://user-images.githubusercontent.com/3835295/47178426-14469280-d2d0-11e8-9df7-5a4d294b5b55.png)
![2018-10-18_12-16-19](https://user-images.githubusercontent.com/3835295/47178442-17da1980-d2d0-11e8-861a-9e348892c3a9.png)

**Comment by katiemcgoff** [comment]
@juliainkster @JohnamLane ready for review in DEV.

**Comment by juliainkster** [comment]
![image.png](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/26a5d98e-cbe7-4f7e-8c8b-b964f7c46f6b)

Hi @katiemcgoff 
After speaking with Kaine, we decided on adding the Namex heading.   
I dropped the navigation to a secondary bar BG colour #38598a 
The dividers are #5475a7  (notice the smaller font) 

Remove the button style from the Logout button and add divider.  

Font-family throughout site should be Myriad-Pro, Calibri, Arial, Sans Serif 

Add some left padding to the logo and align with menu.

NR number load can still use a little curve (not in the mockup)

**Comment by katiemcgoff** [comment]
@juliainkster what does this mean:

>NR number load can still use a little curve (not in the mockup)

I'm reading that as the Load button should have slightly rounded corners. Do you also mean the input box? I'll keep the style in line with the rest of the app inputs and buttons unless I hear otherwise.

**Comment by juliainkster** [comment]
@katiemcgoff 
sorry to be unclear!  The load button should be like the other buttons with no round. The input box (like all the others) should have the slightly rounded corners.

**Comment by katiemcgoff** [comment]
@juliainkster the home link has been removed in your mockup. Was this on purpose, and if so do you want the icon/"Namex" header to link to the home? Or rename the home link "instructions" since that's actually more of what it is? The useful stuff the page contains is the stats and the manual search instructions.

**Comment by juliainkster** [comment]
@katiemcgoff yes to the BC gov logo linking to the home page/starting screen

**Comment by katiemcgoff** [comment]
@juliainkster Ready for review in DEV.

**Comment by JohnamLane** [comment]
@katiemcgoff Please move these changes to test. Thanks!

**Comment by katiemcgoff** [comment]
@juliainkster Ready for review in TEST.

**Comment by juliainkster** [comment]
@katiemcgoff 

- can we change the second level background colour to  #38598a
- second level navigation font-size to 15px,  line-height 23px

I'm trying to match the standard and the vertical delineator is not large enough in our design.   I can't figure out how they are doing it with CSS. Maybe a different sized font class? Have a look at this example? https://www.bceid.ca/ 

Also can we underline the page that we are on?
![image.png](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/1fb7e5d3-90fe-4b7b-ae3d-6ecd792e977c)

I'm the worst!  (but i brought donuts!)

**Comment by katiemcgoff** [comment]
@juliainkster just about ready in DEV (should be by the time you get to this). FYI with these things you will probably have to clear your cache in chrome, it causes me trouble every time I make these UI changes. If you're not sure what I'm talking about, ask me or John.

**Comment by juliainkster** [comment]
@katiemcgoff font-size looks good! 
I think we can move it to test.  

The only last little thing is the vertical line height and style.  
If the divider could have a class with a larger font size at #748bad (I realize I said the opposite before)

**Comment by katiemcgoff** [comment]
@juliainkster I'll put these changes off until tomorrow/Thursday. Can't necessarily squeak these last changes in before full deployment to production. Remind me (or move the ticket back to backlog) on Wednesday or Thursday when the dust settles on the examiner launch.

**Comment by juliainkster** [comment]
Understood!
