### ISSUE TITLE
UI - Recipe steps 

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1030]
Add finger/pointer cursor state to indicate clickability 

Add ability to select multiple conflicts or conditions from Examine screen - users expected a way to select.  CTRL click to highlight multiples is standard.

Remove blue border from .client-info-view
Add 10px padding (to match .conflict-info-view)

Add 10 px padding to .currentConflictName and to NR client info

**Comment by LJTrent** [comment]
Will be completed as part of code with us-refresh.  I need to see if this is an issue now?
