### ISSUE TITLE
Update SOLR Managed Schema for SOLR Cores

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1038]
##### _**Detailed Description**_

Add the two new field types and fields to the managed schema.  
Adapt the field type definitions for using managed synonyms.

Add the two new fields as copy fields.

Re-load the Cores.

##### _**Acceptance Criteria**_
Have the new managed schema deployed for all three cores  and the cores re-loaded. Please see attached file.

(https://app.zenhub.com/files/118046288/ef1744f6-d6b0-4684-91bd-d47723107fe1/download)

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@Associated pull request in namex is waiting for you to approve and merge.

**Comment by WalterMoar** [comment]
Deployed to dev and cores reloaded, but they are not being updated until the TLS issues are resolved.

**Comment by LJTrent** [comment]
@WalterMoar  Checked all cores and the changes are working as expected with the exception of  trademarks because it has not been reloaded yet.

**Comment by LJTrent** [comment]
I have checked all managed schema files for each core and they look correct and appear to be running as expected.

**Comment by WalterMoar** [comment]
Promoted to prod and trademarks loaded.

**Comment by WalterMoar** [comment]
(Will load the remaining production cores tomorrow at 05:00)

**Comment by WalterMoar** [comment]
Prod loaded and jobs enabled.
