### ISSUE TITLE
Update SOLR API to a New Query

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1039]
##### _**Detailed Description**_

Update the SOL query for conflicts and name history.  We will need to talk about trade marks because i think it is different.

**Replace the following parameters with these values:**
&qf=name_compressed^6%20name_with_synonyms

&q=JJHOMEIMPROVESMENTSMAINTENANCE%20OR%20+J&J%20HOME%20IMPROVEMENTS%20&%20MAINTENANCE  --THIS REQUIRES SOME PRE_PROCESSING

**Add the following new parameters:**
&sort=score%20desc
&fq=name_with_synonyms: (%20HOME) --THIS REQUIRES SOME PRE_PROCESSING

**Remove the following:**
&mm parameter

**q pre-processing required:**
A name choice must come in as a compressed name with no spaces or punctuation and no designation.  eg. Above the name is J&J HOME  IMPROVEMENTS & MAINTENANCE INC.

So it needs to come in as a compressed name as well as the name as you have it currently.
So by default the query must be JJHOMEIMPROVEMENTSMAINTENANCE OR +J&J HOME  IMPROVEMENTS & MAINTENANCE INC.

**Additional qf parameters requires:**
take each word in the name and determine if there is a synonym (from your synonym table) 
if there is use it to build your &fq=(HOME) if there is a synonym for more than one word &fq=(HOME DONE SEAN)  

The original &fq was used to facilitate the @ symbol (&fq=name_copy:%20OUTDOORS)  This logic still remains when the user supplies the @  Each one is a separate fq parmeter.   Here is an example:

http://localhost:8983/solr/prod-conflicts/select?defType=edismax&fq=name_copy:%20OUTDOORS&fq=name_with_synonyms:%20(SPORT)&indent=on&q=CANADAOUTDOORS%20OR%20CANADA%20OUTDOORS%20INC.&qf=name_compressed^6%20name_with_synonyms&wt=json

**TradeMarks**

Trademarks should use the same queries as above except it does not include any &fq parameters.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Below are the existing queries. What are the new queries?

```python
        CONFLICTS: '/solr/possible.conflicts/select?defType=edismax&hl.fl=name&hl.simple.post=%3C/b%3E&'
                   'hl.simple.pre=%3Cb%3E&hl=on&indent=on&mm=75%25&q={name}&qf=name&wt=json&start={start}&'
                   'rows={rows}&fl=source,id,name,score{name_copy_clause}',
        HISTORY: '/solr/names/select?defType=edismax&hl.fl=name&hl.simple.post=%3C/b%3E&hl.simple.pre=%3Cb%3E&hl=on&'
                 'indent=on&mm=75%25&q={name}&qf=name&wt=json&start={start}&rows={rows}&'
                 'fl=nr_num,name,score,submit_count,name_state_type_cd{name_copy_clause}',
        TRADEMARKS: '/solr/trademarks/select?defType=edismax&hl.fl=name&hl.simple.post=%3C/b%3E&hl.simple.pre=%3Cb%3E&'
                    'hl=on&indent=on&mm=75%25&q={name}&qf=name&wt=json&start={start}&rows={rows}&'
                    'fl=application_number,name,status,description,score&bq=status:%22Registration%20published%22^5.0'
                    '{name_copy_clause}'
```

**Comment by LJTrent** [comment]
@WalterMoar  Here are the new queries:

![image](https://user-images.githubusercontent.com/35615843/47190905-ddd13d80-d2f8-11e8-828f-52c07a2aa86e.png)

**Comment by WalterMoar** [comment]
Awesome, thanks!

**Comment by WalterMoar** [comment]
@LJTrent - which special characters do I need to handle? Quoted words I assume should be used as a single synonym. A "-" means skip it? What about "@"? Any others?

**Comment by WalterMoar** [comment]
Deployed to dev.

**Comment by LJTrent** [comment]
Please deploy to TEST.

**Comment by LJTrent** [comment]
promote to prod please. we also need Richard's synonyms.

**Comment by WalterMoar** [comment]
We still need to fix the bug that happens when the database it restarted. It's a symptom of a much bigger problem.

**Comment by WalterMoar** [comment]
Used Thor's gunicorn code for a better web server, but that caused the server to hang after a few connections. Fixed the SQLAlchemy initialization code. The bug left is that if the database is restarted, the first user to load do a search will get an error. After that everything will be OK. Fixing this will take a substantial amount of research and rework, so leaving it as-is for now.

Deployed to dev and test.

**Comment by WalterMoar** [comment]
Deployed to prod.
