### ISSUE TITLE
Login - automatically go to login screen, and default to IDir

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#1045]
The app should go directly to the login screen, if the user is not authenticated.
The app, as an internal facing service, should bypass the keycloak login screen and go directly to IDir.

// This will take the user directly to the login screen when they open the app and they are not already logged in
         keycloak.init({ token: token, onLoad: 'login-required' })

// if there is a login button, then this would take the user directly to the idir login screen 
        this.$keycloak.login({idpHint: 'idir'})
or
	keycloak.createLoginUrl({
		idpHint: 'idir'
	});

**Comment by LJTrent** [comment]
Not being done.
