### ISSUE TITLE
Name search (/find) times out when State = All

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1047]
##### _**Detailed Description**_
When you choose state = ALL, and then type into any of the other search fields, you will receive a 504 - Gateway time-out error. This error shows up as a pop-up under the spinner overlay which means it can't be dismissed.

**Comment by kialj876** [comment]
@JohnamLane this is in in test. The changes made here were to only query the api after there are more than 2 letters in the search fields (or if there are none for clearing) - this should speed it up significantly.

**Comment by JohnamLane** [comment]
@kialj876 Please promote to prod. Looks good in test.
