### ISSUE TITLE
Comment improvement with tests

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1055]
Per Eric's suggestion for better testing, add a check for null when adding new comment (rather than just checking for empty string). This is in the InternalComments component, which is currently only used for the decision comment.

From that discussion, Katie also found bug-ish behaviour in NR Details comment (in RequestInfoHeader component) that needs the check as well. This will prevent the brief flash of an empty comment upon save of NR details.

This task includes the code change (Katie) and the tests being written (Eric).

**Comment by ericminio** [comment]
Covered within PR https://github.com/bcgov/name-examination/pull/1071

**Comment by ericminio** [comment]
Now that PR https://github.com/bcgov/name-examination/pull/1071 is merged, I believe we can close this one @katiemcgoff
