### ISSUE TITLE
UI - Search Page - Custom width column widths

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1066]
- Make the column widths user controlled (custom width). Ensure a horizontal scrollbar is added if necessary. Set default column widths per wireframe. On roll over of column edge show icon. [https://app.zenhub.com/files/118046288/490a03c5-c214-4a70-a71e-e77c74270756/download](https://app.zenhub.com/files/118046288/490a03c5-c214-4a70-a71e-e77c74270756/download)

**Comment by juliainkster** [comment]
Persistent across pages

**Comment by LJTrent** [comment]
Not happening in namex.
