### ISSUE TITLE
UI - Search Screen - sort control 

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1067]
- Add mouse-over underline to table column header labels for columns that can be sorted.  (S # 12) 
- Add sort control and icon to column headers for sortable columns (S #13) [https://app.zenhub.com/files/118046288/49a61e25-8dfb-42d8-8168-19c56345eaba/download](https://app.zenhub.com/files/118046288/49a61e25-8dfb-42d8-8168-19c56345eaba/download)

**Comment by LJTrent** [comment]
Not doing it.
