### ISSUE TITLE
Solr API should properly handle quoted words

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#1073]
##### _**Detailed Description**_

The Solr API is sending quoted words through to the Synonyms API as a single term. For example, "hot tub" should be two requests for *hot* and *tub*.

Pytests got missed - need to mock out the results from the synonyms API.

Also, when the word has a minus sign -HOLDINGS do not include this word in the synonyms filter.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Will need to confirm but I think we just need to strip everything other than letters, numbers, spaces, and minus sign, and then split the string on spaces. This will fix this problem as well as 1075.

**Comment by katiemcgoff** [comment]
Covered by #1075
