### ISSUE TITLE
Restricted Words with periods are not caught

### ISSUE THREAD

**Issue by kialj876** [bcgov/name-examination#1074]
Add periods to list of things that are stripped from the string in backend API

**Comment by juliainkster** [comment]
@kialj876 not sure I understand this bug but 

In dev, "D.R." is not identified as a Condition/Restricted word

**Comment by kialj876** [comment]
@juliainkster sorry - no one has merged this into dev yet. I'll let you/Lorna know when someone code reviews it and merges it in.

**Comment by kialj876** [comment]
@juliainkster @LJTrent this was merged into dev this morning and is ready to test

**Comment by juliainkster** [comment]
@kialj876  Looks good in dev - ready to move

**Comment by kialj876** [comment]
@juliainkster @JohnamLane this is ready to test in test!

**Comment by juliainkster** [comment]
@kialj876 in dev D.R. is identified as a Condition/Restricted word.
In test is is not.  

![image.png](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/3534f48f-fc28-4dd6-b5b1-f44594bb5622)

**Comment by kialj876** [comment]
@juliainkster sorry - I forgot which pipeline this was part of - it is not in test yet

**Comment by kialj876** [comment]
@juliainkster @JohnamLane this is ready to test in test now

**Comment by JohnamLane** [comment]
@kialj876 Ready for production.
