### ISSUE TITLE
Update Requestor Message When Consent is Required by a Specific Company

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1076]
##### _**Detailed Description**_
In some situations an examiner will give conditional approval when an applicant must get consent form a specific company to use the name.  When it comes time to make a decision the company shows in the conflict, the examiner selects Consent Required from the condition droplist but the requestor message currently says Rejected... because a conflict was selected.  The requestor message should say Consent Required  from <company name>.

##### _**Acceptance Criteria**_
The message reflects the consent required by company XYZ.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by JohnamLane** [comment]
Mentioned in UI/UX meeting. Raised priority.

**Comment by katiemcgoff** [comment]
@juliainkster @JohnamLane ready for review in TEST.

**Comment by juliainkster** [comment]
@katiemcgoff   Looks good in DEV.  Not seeing it in TEST

![image.png](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/1f3560a2-e530-4ed4-8aa8-7b5a8560f2de)

**Comment by juliainkster** [comment]
@katiemcgoff  cleared my cache and it looks great.  Ready for PROD.

**Comment by katiemcgoff** [comment]
Re-opening - the adjusted message does not get saved correctly upon decision made, due to logic related to an older conflict-related scenario.
