### ISSUE TITLE
Add decision text and conflict(s) to NR details in conflicts/history

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1078]
Add decision text and conflicts to conflicts/historical NR details. This info is important to examiners when making decisions, per Day 1 review.

**Comment by katiemcgoff** [comment]
This covers the front-end change. New task to be logged to pull all the pre-namex decision text and conflicts from Oracle.

**Comment by katiemcgoff** [comment]
@JohnamLane This is ready to test in DEV.

This is added to the recipe steps for NRs in conflicts and history. However I don't think it will ever actually happen in conflicts since those are only approved names which wouldn't have conflicts.

**Comment by katiemcgoff** [comment]
@JohnamLane ready in TEST now.

**Comment by JohnamLane** [comment]
@katiemcgoff Tested in Dev. Ready to move to test.

**Comment by katiemcgoff** [comment]
@juliainkster @JohnamLane Ready for review in TEST.

**Comment by JohnamLane** [comment]
@katiemcgoff @kialj876 This is ready to move to production.Moving to promote to prod.
