### ISSUE TITLE
Need a way to do a Free Search

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1079]
####Background
The examiners are not enjoying doing free searches in the examination screen as they are worried about accidentally doing something to it. We originally thought they would just use the manual search in the examination screen but I can see how it is a different process.  

##### _**Detailed Description**_
Either they get a test one from the hold que or we give them a simple screen off a button to let them test search that doesn't have action buttons. Please do appropriate UI/UX research and mock something up under priority 1.

**Comment by juliainkster** [comment]
Module be preferred. User task (name examination) is interrupted by a call or request to do a "free search" and they should be able to query any name and see the full recipe steps, inform the client (or team member) and then close the module and return to the original task.

**Comment by juliainkster** [comment]
To be called "Name Check"

**Comment by LJTrent** [comment]
Use a test one from the hold queue. That is what examiners have always done.
