### ISSUE TITLE
Add quick reject button on examination screen

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1086]
##### _**Detailed Description**_
Add a button that allows quick rejection with one click and populates the message with the rejected for conflict with the highlighted conflict. Allow the ability to pick up to 3 conflicts, in this action as well as the decision screen.

**Comment by JohnamLane** [comment]
Adding to overall button conversation.

**Comment by juliainkster** [comment]
In the new design prototypes we eliminate the decision screen.  On the examine screen a NE can pick a conflict (1 click) and then reject (2nd click) which is a lot quicker than previously.  They can also select multiple and reject.

**Comment by LJTrent** [comment]
This is addressed in the new UI and use of the scratch pad. Up to three can be selected,
