### ISSUE TITLE
Approved free search is storing rejection of 3rd choice name

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1087]
##### _**Detailed Description**_
I’ve been viewing one of the staff’s reservations.  They gave the client a free search so altered the 1st choice and then approved.  The 2nd choice is showing as not examined but the 3rd choice is showing the name as rejected.  There should never be a rejected 2nd or 3rd choice showing when the 1st choice.
![image.png](https://images.zenhubusercontent.com/5a7899714b5806bc2bc5a0ce/24899730-fff9-4bf8-9b65-c5f1fa84e377)

**Comment by kialj876** [comment]
@JohnamLane ready to test in dev!

**Comment by JohnamLane** [comment]
@kialj876 Testing has failed.
NR 0940269 had 3 name choices that I rejected. On the last on I added a conflict with CRAZY ERIC'S USED CARS. After the name was furnished, I reset it and and the conflict is still there on the third name choice.

**Comment by JohnamLane** [comment]
@kialj876 Pass - this was a caching issue after all. Please promote to Test.

**Comment by kialj876** [comment]
@JohnamLane ready to test in test!

**Comment by JohnamLane** [comment]
@kialj876 ready for prod.
