### ISSUE TITLE
Remove forced comment from pressing the RESET BUTTON

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1090]
##### _**Detailed Description**_
Reset button - remove forced comment when pressing reset. 

The reset comment box should still be displayed but the comment is optional so RESET should be enabled.

**Comment by katiemcgoff** [comment]
not optional, remove comment completely

**Comment by perkinss** [comment]
Ok, I'll just get rid of that popup.  We were just discussing whether we should make it optional but then I noticed the previous comment

**Comment by perkinss** [comment]
Not sure why this is in the backlog, it's done afaik

**Comment by LJTrent** [comment]
This is done.
