### ISSUE TITLE
Name decision - display conflicts when no decision text

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1099]
Many older (pre-namex) NRs do not have decision text, but will have a list of conflicts. If there is no decision text to show in name choice (CompName component) show list of conflicts instead if that data exists.

Depends on #1096 for meaningful data to exist.

Affected by design decision made for #1100 .

~~**ENSURE THE UPDATER IS TURNED OFF HEN THE DATA FIX IS EXECUTED ****~~ n/a

**Comment by LJTrent** [comment]
@katiemcgoff  Is this one still relevant?

**Comment by katiemcgoff** [comment]
@LJTrent Yes - many of the pre-namex NRs have no decision text, only conflicts, because NRO didn't populate decision text like our system does.

**Comment by katiemcgoff** [comment]
@perkinss this is related to #1100. When we talk to examiners about best way to present complete decision text we should keep this one in mind. And it may become moot based on solution for #1100.

**Comment by perkinss** [comment]
Needs test data that looks like the old NRs with just the conflicts

**Comment by LJTrent** [comment]
Not sure if this was ever merged in.  Doesn't look like it.  This will be addressed through a transaction history-phase 5 code with us.
