### ISSUE TITLE
Show complete decision reason in name choice

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1100]
Currently name choice (CompName component) cuts off decision text at 600px (via css). Approvers need to have ability to see complete decision reason.

In complete decision reason view, also show list of conflicts. 

No decision has been made at time of logging this bug as to how to display this - as popup? Expand on screen? Always show full decision text + conflicts? TBD. Related to (and affects work done on) #1099 .

**Comment by katiemcgoff** [comment]
![2018-10-30_9-19-20](https://user-images.githubusercontent.com/3835295/47733198-f4df2c00-dc24-11e8-9e37-4dcca969b552.png)

**Comment by perkinss** [comment]
I can see a few choices.

1. Remove the white-space nowrap from css
 2. Remove the whites-space nowrap and remove the width
 3. Add a tooltip that shows the full text on hover
 4. Add a link that pops open a modal
... and probably there are more.

**Comment by perkinss** [comment]
With a the whitespace no-wrap removed, but width the same:
<img width="1424" alt="screen shot 2018-11-05 at 3 55 04 pm" src="https://user-images.githubusercontent.com/405204/48079795-fa96bd80-e1a0-11e8-9fbe-d84b8da4c5d6.png">

With the whitespace no-wrap removed, and full width:
<img width="1444" alt="screen shot 2018-11-05 at 3 56 36 pm" src="https://user-images.githubusercontent.com/405204/48079796-fa96bd80-e1a0-11e8-9246-67c21554b6a6.png">
Keep in mind how this change would impact the Examine page.
It's also important to note the decision reasons can be identical for all three names, or they can be quite different, or they can be a mix of reasons that are different or the same.  

I would recommend a popup or modal or tooltip option.  A basic tooltip is like this: 
<img width="1399" alt="screen shot 2018-11-06 at 8 56 52 am" src="https://user-images.githubusercontent.com/405204/48080209-fc14b580-e1a1-11e8-996a-e41541a736ef.png">

but we would want to update the styling, such as the default width :) Just didn't have time last night to do that ... Also: It can appear with either a click or hover, or focus, or all these things.

Another option is a modal, which darkens the current page and displays the text in a small window on top of the current page.

**Comment by forgeuxGH5** [comment]
My choice would be the tooltip / pop-over or a Show more... / Show less... expand / collapse, but... 

I would want to ask the Examiners a couple of things:
1) Do they want to compare the various comments or for some reason be able to see all the full text at the same time? 
2) Do they want to copy text from a comment?

If they don't want to do either of these then the tooltip / pop-over would be faster - we'd need a bit of delay (not sure if our component has a default but 0.5s would be a good start). If they want to see multiple full comments we'd probably have to use a Show more.../Show less... expand/collapse (which would also let them copy), or if they just want to copy text then we could go with a click / pop-over design (that would have to be dismissed).

Show more...
![image](https://user-images.githubusercontent.com/26335434/48102608-c511c480-e1e0-11e8-8f35-ac0fc4306519.png)

**Comment by perkinss** [comment]
The feedback from the customer (thanks for the research, @forgeuxGH5) as of this morning is that when they are examining names, they do not need to see the entire rejection decision, and being able to see it would interfere with the rest of the screen real estate they need to make their decisions.

However, when someone calls and they need to look at a completed name, they need to see the entire decision reason for every single rejected name, and they don't need it in a popup because they want to see them all at once so they can explain to the customer on the line as to why for example all three of someone's names were rejected.

This seems to indicate that we may need a separate component for displaying a completed NR that shows all the details.

**Comment by forgeuxGH5** [comment]
I think that looks good - to make it easy to read we want about 8-10 words per line - so I think the width is pretty good as is.

**Comment by perkinss** [comment]
This should probably be closed?

**Comment by forgeuxGH5** [comment]
Yes - I think so. It's in and working for the Examiners.

**Comment by LJTrent** [comment]
Looks like it was fixed.  Also, there will be a transaction history added to namex to teh code with us effort so they can look there.
