### ISSUE TITLE
Set Expiry Date to Just a Date not a DAteTime

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#1101]
See attachment email from business.

Considerations:
- store with or without time?
- what's getting back to NRO?
- what is customer seeing? time or no time?
- should we set time to begin/end of day rather than based on actual time of day?
- timezones
- should we show time on screen? is it relevant at all?
- consider what expiry date is used for, checking status, whether to show buttons, etc.

**Comment by katiemcgoff** [comment]
[FW_ expiry date for approved name reservations_.pdf](https://github.com/bcgov/name-examination/files/2530730/FW_.expiry.date.for.approved.name.reservations_.pdf)

**Comment by katiemcgoff** [comment]
Related/same issue reported by examiner. Included to illustrate issue:
> I’ve noticed that name requests expire in NameX before the date stated in the correspondence sent out to clients.
> 
> As a result of the early expiration timings, NameX and NRO disagree with each other on the last indicated day that an NR should still be active; one system shows the NR as being expired while the other system shows not expired.

![namex](https://user-images.githubusercontent.com/3835295/48797609-84717b00-ecb7-11e8-8a1e-e92b48e1f7fe.PNG)
![nro](https://user-images.githubusercontent.com/3835295/48797616-889d9880-ecb7-11e8-85b7-fecdbb91ca47.PNG)

**Comment by perkinss** [comment]
I see that the submitted date is also off.  It's not just the time, it's the date.  The submitted date on NRO is 12 hours earlier, giving a different date.

If the time is off by 12 hours for the submitted time, pushing the date ahead in namex, I wonder whether that is the reason the expiry date appears to be a date ahead.

I wish it was as simple as saying, hey, it's just a timezone issue; however, 8pm on the 23 in NRO to 7am on the 24 the next morning is not the PST time zone diff... this is more like PST diff * 1.5.  

The plot thickens!

**Comment by perkinss** [comment]
Related to #965

**Comment by LJTrent** [comment]
display a date in NAmex.  sends back a date/time currently to NRO in UTC  but it is not used in NRO.
