### ISSUE TITLE
STATS - Create daily report on Stats - Priority/Draft/Hold

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1104]
##### _**Detailed Description**_
Create a daily stat until we have it on a dashboard. The stat must include the following:
On Hold
Priority
Draft
It would be great to include:
Priority over 24 hours old
Last 3 days of submissions

**Comment by LJTrent** [comment]
Done as a jupyter notebook.  Cannot be implemented so that it can be run automatically until data lake platform is set up.  SO currently no one is running it,.
