### ISSUE TITLE
EDIT - When I edit I don't want it to come out of the Que

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1105]
##### _**Detailed Description**_
NR's will be edited when in the que and may just insert a comment. It should not pull these edits out of the que. Please come up with a plan to address this issue, then we can prioritize. Other scenarios could include:
I want to edit the name while I am examining it and I want to keep it in my name
I want to edit the name while it is on Hold and I want it to go back to Hold
I want to edit the name while it is in Draft and I want it to go back to draft after
I

INFORMATION FROM EXAMINER
Concerning NR 2178532, I just thought I would pass along that editing name requests in the queue which have not yet been pulled appears to immediately pull them out of the wait queue as if they had been jumped.

We received email correspondence from a client who wished to provide some additional clarifying information regarding their name request; as the request is not a priority request and will not be examined for at least a few business days I thought I would take advantage of the new note system to pass along the client’s information.

With the intention of just leaving a note prior to examination, I entered the NR number into the Namex search bar and loaded it. After loading the NR it appeared as a name in the hold queue would appear with the option to sign the NR out by clicking the Examine button. Upon clicking only the Edit button the NR was automatically pulled out of the wait queue and signed out under my IDIR effectively jumping the queue on the NR.

The expected result of what I was trying to do was that I would pull up the correct NR and leave a comment on it while being able to leave the NR in the wait queue in its appropriate position.
The actual result of what I did was that the editing an NR existing in the wait queue automatically pulled the request and jumped the queue on it as if clicking the Examine option.

1)	Entered NR number into search bar near the top of the Namex page and clicked load
2)	NR loaded with the appearance of an NR that would be found in the hold queue (Examine button displaying as opposed to Decision button)
3)	Clicking Edit in order to leave a comment for when the NR is actually examined changed the NR to the appearance of an in progress NR (Decision button displaying)
4)	Left comment and clicked save
5)	Pulled up in progress NRs using the Search function and confirmed that the NR I left a comment on had been pulled under my IDIR as if it had jumped the queue

NR 2178532 is not a priority request and was submitted on October 18 at 12:17 AM, at the time I left a comment on the NR I believe the name examination team was processing October 14 at 2:27 PM. 

I’m not sure if this design is intentional or if there is any way to leave comments on a name request prior examination while leaving the request where it is in the wait queue.

Kristopher Yee

**Comment by LJTrent** [comment]
After discussion with Kial and Thor, when an NR is DRAFT and is selected on LOAD or from the Search screen, it gets set to INPROGRESS and allows the staff to edit the NR submission details.  When it is SAVED, the status must be set back to DRAFT.  Kial talked about setting an edit flag in the front-end to  control putting it back to DRAFT in the position that it was originally in the queue.

**Comment by LJTrent** [comment]
Done.
