### ISSUE TITLE
Remove the NR # from the  NR Conflict Text

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1108]
##### _**Detailed Description**_

Currently when an NR is selected as a Conflict, the name-NR ##### is displayed.  This is also what is included in the comments on a client notification letter.  The y cannot give out other people's NR # so this must be removed from the text.  Just confirming with Jennifer if she want the NR removed altogether or if she wants <name>-NR 0000000.  

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
Replace NR # with "NR"

**Comment by thorwolpert** [comment]
Seems sorta weird to keep any of it then, if it is meaningless.
