### ISSUE TITLE
Add Registration Number to the SOLR Trademark Core

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1109]
##### _**Detailed Description**_
Add the Registration Number to the trademark core.  We may as well leave the application number but it has come to light they need the registration number instead if they use it as a conflict.

This will also require a re-load of the trademark core as well as changes to the UI to remove the application number and replace it with the registration number as well as in the decision window when it is selected.  We will need the core update before the other work can be started.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
When done, please create UI and/or API change ticket(s).

**Comment by LJTrent** [comment]
@JohnamLane  I already added the other trademark issues as I need them for sprint planning.
