### ISSUE TITLE
Add Submitted Statistics for the Examiner

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1111]
##### _**Detailed Description**_
The examiners need the stats for what is submitted as well as what they have completed today.  Currently, they have a page in COBRS that they navigate to to get what was submitted. 

##### _**Acceptance Criteria**_

Must not have a performance impact.
Must include: 
Total Priority Request (DRAFT state)
Total Regular Request Submitted (priority=N) for Day 1, Day 2, Day 3, Day 4
Total Regular Request Submitted Prior to those days listed above:
Total Count: if all numbers above.

They also want to see how many they have completed today.  This would be a running total for the examiner who is signed in. If possible with our performance impact show the average time to complete a name request. If they are not an examiner we  may want to hide this stat.

Please see attached screen shot.
![examiner-stats](https://user-images.githubusercontent.com/35615843/47821457-f6d8e600-dd1d-11e8-994a-2f169184c054.JPG)

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by ericminio** [comment]
on it...

**Comment by ericminio** [comment]
Counts:

Priority requests: state DRAFT priority Y

For each day:
the count of requests still DRAFT today and that were submitted that day (aka from events table, select distinct nr_id with state DRAFT on that day)

**Comment by ericminio** [comment]
@Kaineatthelab note that from a conversation with DJ, we got that she would like to have the count for each day and not only the first 4 and a remaining bucket for the older ones.
Will you please share your insight/preference on this?

cc @LJTrent

**Comment by ericminio** [comment]
Black and green is just for fun of course ;) 

With a small extract from Dev:
<img width="439" alt="screen shot 2018-11-02 at 3 25 30 pm" src="https://user-images.githubusercontent.com/130439/47943534-b317e500-deb3-11e8-947b-95c126fa2aba.png">

**Comment by ericminio** [comment]
This 46 includes all requests in DRAFT and priority Y, those older than 24 hours included.

@thorwolpert suggested that this way of counting priority requests is not accurate. 
As I mentioned it during daily scrum today, I need more details from him.

**Comment by Kaineatthelab** [comment]
Yes, can it be separated out though? The ones that are older than 24 hours are important and it would be beneficial to know so they can action them asap😊


Kaine Sparks
Deputy Registrar |  BC Registries and Online Services<http://www.bcregistryservices.gov.bc.ca/>
Service BC
Ministry of Citizens’ Services
T: 778-698-1404 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”
[Innovation]

**Comment by ericminio** [comment]
Currently we can separate out requests by submission date.

For example we could display
| October 29   |  34 | 3 |
| October 28   |  17  | 7 |
| October 27   |      5  | 2 |

which could mean "We currently 5 draft requests submitted on October 27, 2 of them are currently a priority"

The info that we don't have yet is when a request became a priority. So for example, the 2 priorities of October 27 could have become a priority on October 29. But currently we don't know that in our postgresql namex database. My understanding is that @thorwolpert asked for the priority_date to be sent to us. 

@Kaineatthelab Will you have a minute for a discussion to decide what to do about this?

**Comment by Kaineatthelab** [comment]
Yes please, we can discuss in about an hour.


Kaine Sparks
Deputy Registrar |  BC Registries and Online Services<http://www.bcregistryservices.gov.bc.ca/>
Service BC
Ministry of Citizens’ Services
T: 778-698-1404 | Web: http://www.servicebc.gov.bc.ca<http://www.servicebc.gov.bc.ca/>
“Access to government services made easy”
[Innovation]

**Comment by ericminio** [comment]
yes!
Thank you

**Comment by LJTrent** [comment]
Kaine has decided to go in a different direction so this ticket is closed.
