### ISSUE TITLE
Statistics view

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1112]
Currently showing "Not Examined" and "Hold" numbers on the home page.  Request to also show number of Priority Requests. 

Determine if there are any other statistics or views that would be valuable.  Homepage dashboard concept?  Incorporated into Search screen?  Keep/repurpose the Stats page?

**Comment by LJTrent** [comment]
@juliainkster  Just wanted to let you know.  I have also created a separate ticket that shows what they want for the numbers.  Eric and I plan to work on that tomorrow.  Please continue with  what they would like the dashboard to me and for which audiences.

**Comment by juliainkster** [comment]
#1111

**Comment by LJTrent** [comment]
Jupyter notebooks and other methods will be sued to supply stats.  Thor has already created a jupyter notebook that need a platform to urn automatically.
