### ISSUE TITLE
Search page - date and time ranges

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1113]
NEs are requesting statistics/data for particular time ranges (2:15 to 3:30 for example).  
We need to understand *why* they are doing this and determine if we need a date and time picker or an advanced search option. 

Date ranges (last 7 days for example)  might not meet their requirements.

**Comment by juliainkster** [comment]
This may be used for auditing purposes only. Consider search and statistics together.

**Comment by LJTrent** [comment]
Will be addressed through the data lake/analytics.
