### ISSUE TITLE
UI - Search Screen - Priority change indication

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1121]
As a NE I want to know if there was a change of priority so that when I look at the submitted date and see it was submitted more than 24 hours ago I know it's not a system error and that we are not behind processing priority queue.

**Comment by juliainkster** [comment]
Scott to mock-up icon indicator on search screen beside Submitted date with roll-over to show the date and time the priority changed.

**Comment by LJTrent** [comment]
You can see this by last update date and priority setting in the search screen.  We could add priority date to the banner.
