### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#1123]
As a NE I want the option to toggle to a UI that uses darker colours to reduce eye strain.

Dark UI is said to reduce eye strain and fatigue for applications that are used for a long period of time. 

“…most studies have shown that dark characters on a light background are superior to light characters on a dark background (when the refresh rate is fairly high). For example, Bauer and Cavonius (1980) found that participants were 26% more accurate in reading text when they read it with dark characters on a light background.”

"While the contrast level is greater with dark text on light backgrounds, the same high contrast level causes eye strain in extended period of time (think >5 hours) for those that are in front of a screen for such a time period."

**Comment by LJTrent** [comment]
New UI addresses eye strain based on examiner input to a new UI.
