### ISSUE TITLE
Cancelled requests are written to Oracle as ADMIN transactions

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#1125]
##### _**Detailed Description**_

When an approved name in NameX is cancelled, it is being sent to Oracle with a transaction.transaction_typ_cd value of ADMIN. This is probably not correct, as the Solr feeder ignores ADMIN transactions but handles CANCL transactions by removing the name from the possible.conflicts core.

This query lists all cancelled requests that are ADMIN transactions with the "namex" user:

```sql
SELECT   *
    FROM TRANSACTION NATURAL JOIN event
         NATURAL JOIN request
         INNER JOIN request_state ON event_id = start_event_id
   WHERE transaction_type_cd = 'ADMIN' AND staff_idir = 'namex' AND state_type_cd = 'C'
ORDER BY transaction_id DESC
```
##### _**Acceptance Criteria**_

 - Confirm that setting the transaction_typ_cd to CANCL is correct, works correctly in NRO and any outputs that may be created.
 - Update the code to set the correct transaction_typ_cd.
 - After deployment, datafix the transaction table to use CANCL. Then update the name_transaction table and change the solr_status from I to P for the given transactions IDs.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
@LJTrent Can you or someone else confirm that this makes sense? I think that switching to CANCL from ADMIN is correct but I'm not 100% sure.

**Comment by LJTrent** [comment]
@WalterMoar  yes your assumptions are correct.  This will also mean an update to the api that sends the cancellation back to oracle.

**Comment by LJTrent** [comment]
new ticket created on entity board.
