### ISSUE TITLE
Add the Corporation Type and Home Jurisdiction to the Corporate Display & COLIN API

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1126]
##### _**Detailed Description**_

The real issue is that the words BC CORPORATION are hard-coded in the Corporate Details panel.
Examiners think the system is displaying the wrong one but we just dont get it from the colin database.

They are also asking for home jurisdiction when it is not a BC company.  This is a new ask and can be done with this work.

The corp type that is displayed in the Detail pane for corporations is incorrect.  Eg. 
XS0069422 is displayed as a BC CORPORATION but it is an XPRO SOCIETY.

 

I suspect the wrong column is in the query for corp_type_cd.
![image.png](https://images.zenhubusercontent.com/5a70ead94b5806bc2bc4f2c4/c962b633-fb51-46f4-9c16-4674fe37d77d)

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by perkinss** [comment]
There will be a log statement in the chrome console that gives the conflict response, something like 'Corp Conflict response:' followed by the data json.

**Comment by LJTrent** [comment]
Replaced by ticket on the entity board.
