### ISSUE TITLE
Need Date & Time Priority was applied

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#1128]
##### _**Detailed Description**_
Currently Priority is a Y|N flag. We need the actual date+time that priority was added so that the 24hr clock within which to complete priorities can be monitored correctly.

**Comment by LJTrent** [comment]
@juliainkster What is the intent?  Dos this need to be on the examine screen, search screen?  Do they actually need the date timestamp or do they need to know how old it is?

**Comment by juliainkster** [comment]
@LJTrent  I created an issue in UX #1121 for research/design. 
Scott was going to include the concept we talked about in the next iteration of the search screen mock up.

**Comment by LJTrent** [comment]
Done.  Not displayed.  Will be displayed in transaction history.
