### ISSUE TITLE
Add date & time for the request decision.

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#1129]
##### _**Detailed Description**_
The date and time that the final decision was completed should be recorded in the Request record.

**Comment by LJTrent** [comment]
@juliainkster What UI implications does this have?

**Comment by perkinss** [comment]
And if it was rejected and reopened, should there be a timestamp for each decision / reopening?

**Comment by LJTrent** [comment]
This will be addressed in the transaction history.
