### ISSUE TITLE
ZenHub Orientation

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#113]
---
---
##### _**Detailed Description**_
Each team member to learn how to enter and manage their issues in ZenHub.
##### _**Sprint Goal**_
Get the team up to speed on zenHub so that team members can be keep track of their own work as well as the team see's what work is on deck for the sprint and its progress.
##### _**Acceptance Criteria**_
- All team members can open and understand the zenhub board
- All team can  search and filter Issues from the board
- All team members can look at their workload for the sprint.
- Scrum masters can review velocity and burndown charts.
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
John, and Varek have had their zenHub orientation.

**Comment by megwhetung** [comment]
Hi @LJTrent - I'm feeling comfortable with ZenHub.

**Comment by LJTrent** [comment]
@megwhetung  ok.  great.

**Comment by LJTrent** [comment]
Everyone who is going to use it has had some orientation.  if anyone had questions please ask.
