### ISSUE TITLE
Solr - treat all initials the same

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1134]
##### _**Detailed Description**_
Queries for all of the following initials should be treated equally. This could be extended to initials up to 3 characters long.
aa
a.a.
a. a.
a&a
a & a
a.&a.
a. & a.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Done.
