### ISSUE TITLE
Solr - Results that match the start of the phrase > hits with the query in the middle

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#1137]
##### _**Detailed Description**_
Solr searches for all terms in the query, and it locates them throughout the phrase in the results. Examiners need results that match the start of the phrase and follow on in the same order to be ranked higher than out of order hits that don't respect the start of the query phrase.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Done. with buckets.
