### ISSUE TITLE
Add Registration Number to Trademarks

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1139]
##### _**Detailed Description**_
Examiners require the registration number for  a trademark that has been selected as a conflict as this is what the client will need do to any follow-up for consent or terms of use with the registered trademark owner.

We are not sure if all trademarks have a registration number or if only registered trademarks have a registration number.  

There are a number of tasks to completed this ask:
1) Display the registration number in the trademark section of the examine page.
2) update the decision section to include the registration number instead of the application number.
3) determine if all trademarks of all states that are currently included (active) if they have a registration number.
4) determine what to do if only a subset of trademarks have a registration number.

**Comment by JohnamLane** [comment]
The registration number has been added to the trademarks index and a fresh version is in dev. Only 75% of trademarks include the new field, so it can't replace the application number directly on the decision screen. More planning needed.
