### ISSUE TITLE
Consent Company Not Reflected in the Approval

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1145]
##### _**Detailed Description**_

Examiners can select a conflict that will name a company that the submitter will need to get approval from before they can use the name.    The requestor message is formatted correctly and does show the companny name but there are few pieces missing.

1) In Namex, the decision text listed under the name that is conditionally approved does not have the conflict listed.   
2) The message to requestor somehow doe snot include the companyname when it gets back to Namesp.
3) The conflict (compay names do not go back to namesp in the decision)

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
Fixed in pull request #1146 connected to original issue #1076 .
