### ISSUE TITLE
SEARCH - Display no results

### ISSUE THREAD

**Issue by Kaineatthelab** [bcgov/name-examination#1157]
##### _**Detailed Description**_
Add a no results indicator when there is no results in the conflict pane and the history pane.
#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
No impact to performance
No results indicator shows when there is no results

**Comment by perkinss** [comment]
Styled it so that it looks like the same indicator as given by the tables for conflicts and trademarks.

<img width="1339" alt="screen shot 2018-11-09 at 4 09 47 pm" src="https://user-images.githubusercontent.com/405204/48294582-ed483000-e439-11e8-85d1-cfa2a6bfdd0a.png">

**Comment by LJTrent** [comment]
Will be dne with namex UI refresh- phase 3
