### ISSUE TITLE
Build an Exact Match for Conflicts

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#1159]
##### _**Detailed Description**_

Build an exact match list of conflicts.  This includes:

1) exact match of all words without punctuation  and without the designation.

##### _**Sprint Goal**_
Provide the exact match as the examiner gets in COBRS today.

##### _**Acceptance Criteria**_
-Test drive exact match with punctuation in the name such as dots, commas, ampersands ...
- Test drive the removal of designations
- Test drive  the removal of double letters
- test drive adding these conflicts to the conflict list in the UI
- test drive highlightling matching words in the exact match conflict list.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by ericminio** [comment]
A proposal for that feature is ready for review:
the front-end: PR https://github.com/bcgov/name-examination/pull/1166
the back=end: PR https://github.com/bcgov/namex/pull/415

**Comment by LJTrent** [comment]
Done.
