### ISSUE TITLE
setup a set of test services that have prod data

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#1160]
##### _**Detailed Description**_
Create a new deployment (prefixed with pprod_) that has production data.
Use the _test namespace to setup the new services.

**Comment by WalterMoar** [comment]
Pod pprod-solr in test is running. Starting the dataimports.

**Comment by WalterMoar** [comment]
Solr core names is loaded.

**Comment by WalterMoar** [comment]
Solr core trademarks is loaded. Solr is ready to go.
