### ISSUE TITLE
Solr: datafix to corporation states is not picked up

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#1168]
##### _**Detailed Description**_

The registries DBAs updated a corporation state from active to historical, but we only pick up insert state changes.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
DBAs have been asked to do an insert so that the trigger is fired.
