### ISSUE TITLE
COBRS like search

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#1171]
##### _**Detailed Description**_
Determine the algorithms used in COBRs, recreate them in NameX and display them in a similar manner in another window.

1. get design / mock up from Scott
2. get algorithm details from the mainframe team (Approx 14 PL/1 segments)
 and the implement it.

**Comment by thorwolpert** [comment]
the mainframe team thinks they can get the description to us by Wed Nov21. With the flu and down a man that's pretty quick to accommodate our ask.

**Comment by LJTrent** [comment]
Not happening.
