### ISSUE TITLE
Examiner status

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#1178]
##### _**Detailed Description**_
Examiners should be able to self-select a category that describes their current work activity. Approved categories should be set by managers, that best describes the work assigned to an examiner.
Example categories are: Examining, Answering Phones, Break, Away, Research, Calling Customer, etc.

**Comment by forgeuxGH5** [comment]
Do we have room for it here with the new stats info?
![image](https://user-images.githubusercontent.com/26335434/48744106-bb458380-ec1a-11e8-93c8-8606a8371507.png)

**Comment by LJTrent** [comment]
Will be completed as part of the data lake/analytics work.
