### ISSUE TITLE
Get Next Name Request

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#118]
[Information About NRO Applicant and other contacts.docx](https://github.com/bcgov/name-examination/files/1872904/Information.About.NRO.Applicant.and.other.contacts.docx)
#### **Story**
As an examiner I want to get the next available name request so that I have control over when I conduct a names examination.

##### BDD Pseudo-Code (GIVEN "context" ... AND "more context" ... WHEN "this action occurs" ... THEN ..."result")
GIVEN a name request has a Draft request status and  the current user is an examiner and the NR  is not currently being examined by someone else                   
WHEN the examiner clicks Next NR
THEN retrieve the next name request from the names examination database.

##### _**Acceptance Criteria**_
-get the next available NR from the database.
-Stamp the examiner's credentials (IDIR) on the NR row.
-set the NR status to " IN PROGRESS", currently "HELD"
-set  the reservation_count by 1 (for new NRs should be set to 1, for re-submission should be set the prev, nr reservation_count + 1.)

##### _**Logic**_
-Retrieve the oldest name request that has a request status=NE in the following priority: jumpq, priority and none.
-Currently the examiner hits the Enter key to get the next one to be examined.

##### _**Issue Checklist**
- [x] BDD Pseudo-Code 
- [ ] Estimate
- [x] Priority Label
- [x] Story Label 
- [x] Assignee
- [x] Linked EPIC

##### _**Definition of Done**
- [ ] Analysis/Deisgn
- [ ] DB
- [ ] UI
- [x] Integration Points 
- [x] Logic
- [ ] Test Script
- [x] Roles/Security

**Comment by JohnamLane** [comment]
Current state of ordering is as follows, but I will confirm if this is desirable:
1) Priority Request, with Jump Queue flag
2) Priority Request, no Jump Queue flag 
3) Regular Request, with Jump Queue flag
4) Regular Request, no Jump Queue flag

Order by oldest to newest within each group
