### ISSUE TITLE
Multi-Phase Namex UI Enhancements

### ISSUE THREAD

**Issue by bcdevex** [bcgov/name-examination#1250]
<p>This issue has been auto-generated to facilitate questions about
<a href="https://bcdevexchange.org/opportunities/cwu/opp-multi-phase-namex-ui-enhancements"> a paid opportunity</a> that has just been posted on the
<a href="https://bcdevexchange.org">BCDevExchange</a>.</p>

<p>To learn more or apply, <a href="https://bcdevexchange.org/opportunities/cwu/opp-multi-phase-namex-ui-enhancements">visit the opportunity page</a>.
The opportunity closes on <b>Friday, May 10th, 2019 at 16:00 PDT</b>.</p>

**Comment by LJTrent** [comment]
Here is the attached spreadsheet with the detailed requirements.
[Namex-UI-Refresh Detailed Releases for Code with Us.xlsx](https://github.com/bcgov/name-examination/files/3118569/Namex-UI-Refresh.Detailed.Releases.for.Code.with.Us.xlsx)

**Comment by cnewfeldt** [comment]
https://github.com/bcgov/namex/blob/master/api/config.py may want to remove your keys.

**Comment by thorwolpert** [comment]
Those are test keys used for the tests only, much like the supporting jose libraries have in their test suites.

**Comment by NicoleCNelson** [comment]
Hi - I'd like to confirm that a few individuals from one company can put forward a proposal for this opportunity.

**Comment by eggsandbeer** [comment]
I'd like to apply for this work. Thanks.
[Proposal.txt.zip](https://github.com/bcgov/name-examination/files/3143592/Proposal.txt.zip)

**Comment by mrosenlund** [comment]
Hi, in terms of listing open source projects up to a maximum of 3. If there are a few individuals putting forward a proposal together should it be 3 each or still max 3 for the group?

**Comment by rongorodetsky** [comment]
Hi @LJTrent , I would like to apply for this opportunity on behalf of my company, Olivewood Software. The **Proposal Evaluation Criteria** on the project state `Please put all of this information into a document, ensure it is easily identified (company name) and attach it to a comment in the github issue posted.` but I see that you've commented above to submit the proposal through proper channels of the DevExchange. We have completed the submission through the DevExchange and I won't be attaching it to this comment per the above, but please let me know if I misinterpreted anything.

**Comment by LJTrent** [comment]
Status update:
 There have been 16 proposals submitted.  I am currently scoring them and will update the status at the end of today.
Thank you.

**Comment by bcdevex** [comment]
This opportunity has been assigned

**Comment by aardvark82** [comment]
Are you telling all applicants about status or should we consider our proposal to be rejected if we haven't heard from you? @LJTrent
