### ISSUE TITLE
Cancelled Name Requests

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#132]
##### _**Story Sentence**_ (As a "user type" I want a "goal" so that "benefit".)
As a names examiner, I want to keep cancelled names in the system so I can see more detail re: cancellation reason and refund info, timeline. 

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] User Story :one:
- [ ] Priority Label :one:
- [x] Story Label :one:
- [x] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results

**Comment by knmurray** [comment]
Is associated with Story #139
