### ISSUE TITLE
Search Name Requests

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#136]
----
----
##### _**Story Sentence**_ (As a "user type" I want a "goal" so that "benefit".)
As an examiner, manager, administrator or supports staff I want to be able to search the names requests to  fulfill a number of requirements so that I can address client requests.  

The functionality must include:
-as getting a list of name requests on-hold
-being able to select an open the NR from the search screen
-Look for an NR when you don't have the NR # by specifying the submission date range, applicant last name with wildcard characters, search by status, priority.
-list the NR #, request type, status, priority, applicant, contact name, number, # of days since submission
-be able to sort by each column in the search results

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] User Story :one:
- [ ] Priority Label :one:
- [x] Story Label :one:
- [x] Linked EPIC :two:
- [x] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----
----

**Comment by juliainkster** [comment]
Research/Inspiration:

http://fooplugins.github.io/FooTable/index.html 
Notice drop down to filter search results.

https://fancygrid.com/samples/filtering/server
Search by columns
