### ISSUE TITLE
Determine Thesaurus groups

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#195]
##### _**Detailed Description**_
Determine how groups are defined in the mainframe thesaurus.

##### _**Sprint Goal**_
Understand the existing thesaurus.

##### _**Acceptance Criteria**_
- understanding the groups.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
The thesaurus had a related_id but no group name.  All terms with the same related_id are part of the same group.  This is a complete judgement call on the part of the senior examiner.
