### ISSUE TITLE
Research Final Reservation

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#196]
##### _**Detailed Description**_
Resubmit NRO
Match by name choice, email, phone # of applicant 

##### _**Sprint Goal**_
Applies to getting ready for sprint 3.

##### _**Acceptance Criteria**_
- determine all teh step sand data required as part of reservation tracking.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Final reservation concept has been replaced by the idea of keeping track of the reservation count, set to 1 the first time a submission is done.  then if the client does a re-submission or the examiner determines that a re-submission was done then the reservation count = new submission reservation_count + the old reservation_count when the approval is done.  Although there is a policy that there can only be three extensions hence the final reservation it will be up to the examiner to decide.
