### ISSUE TITLE
Recruitment for User Research

### ISSUE THREAD

**Issue by megwhetung** [bcgov/name-examination#20]
_Email blurb to use in outlook meeting request for internal staff [replace my name and role with yours if you're sending it out]:_

I’m Meg Whetung, Service Design Specialist, Government Communications & Public Engagement, reaching out from the project team researching improvements to the Names Examining process. You have been recommended as a valuable person for us to gain insights and feedback from.
We'd like to meet you for an informal interview to hear about your experiences and needs related to Names Examining:
- Where: at your office (your workstation if possible)
- What to expect: an interview and observation of how you interact with the names examining application

We hope this proposed time works for you – please let us know ASAP if we need to reschedule for a more convenient time. And if you have any questions about this project please get in touch, we're happy to clarify.

Thank you in advance for your time - we're really looking forward to hearing your perspective and feedback to inform improvements to the names examining application.

_Email blurb to use in initial contact email to external stakeholders:_ 

The GCPE-GDX Service Design Team is working in partnership with Service BC to redesign the existing mainframe application for names examination, to create a better user experience for names examiners, leverage modern technology and enhance the client experience. 

You’ve been identified as a key person for the research team to talk with to help identify user challenges and find opportunities to improve the names examining process. 

We'd like to meet you for an informal interview to hear about your experiences and needs related to Names Examining:
- Where: at your office (your workstation if possible)
- What to expect: a one-hour session including an interview and observation of how you interact with the names examining application

We’re scheduling interviews for the week of February 5-9. Please let us know if you are willing to meet with us during this time. We will then follow up with a meeting invite.

Thank you in advance for your time. Your input and feedback are a valuable component of this project. If you have any questions about the project or the interview process, feel free to contact Meg Whetung, Service Designer, at 250-893-1170.

**Comment by megwhetung** [comment]
Script for names examining staff to recruit citizen users: 
We're currently doing user research to inform improvements to the name request process. Would you be interested in participating in a short interview about your experience with the process? It would be a one hour session, in a location that's convenient for you (like your home or office), and you would receive a $50 gift card as a thank you for your time. If you're interested, you can contact our research staff to find out more and book a session, at 250-893-1170 or meg. whetung@gmail.com.

**Comment by megwhetung** [comment]
@JohnamLane Can you take a look at the phone script above for recruiting citizens and let me know what you think?

**Comment by JohnamLane** [comment]
OK, I have sent that note to the Names Staff.

**Comment by megwhetung** [comment]
@JohnamLane I just realized I accidentally listed my gmail instead of my gov email in the script blurb above for names examining staff to recruit citizens. Could you follow up with them to provide this correction? It should be meg.whetung@gov.bc.ca. Thank you!
