### ISSUE TITLE
Examine UI Design 

### ISSUE THREAD

**Issue by megwhetung** [bcgov/name-examination#209]
##### _**Detailed Description**_
Consolidate and refine sketches done so far into a design that can be passed on to devs and communicates what the examine screen should look like and how an examiner would interact with it.
##### _**Acceptance Criteria**_
Design (static mockups or simple clickable prototype) delivered to developers showing how name request details and examination recipe will be displayed (structure of the page) and how the examiner will interact with it at a high level. 
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@megwhetung  Hi, I have attached the docs I just sent you via email here.  You can use them if you like.
[NR-APPROVED-EXTENDED.docx](https://github.com/bcgov/name-examination/files/1798692/NR-APPROVED-EXTENDED.docx)
[NR-IN PROGRESS-page-1.docx](https://github.com/bcgov/name-examination/files/1798693/NR-IN.PROGRESS-page-1.docx)
[NR-IN PROGRESS-DECISION-page2.docx](https://github.com/bcgov/name-examination/files/1798694/NR-IN.PROGRESS-DECISION-page2.docx)

**Comment by juliainkster** [comment]
Sprint 2 UI exploration:
https://docs.google.com/presentation/d/1dfvQjHXbwcgjLI48pn7PZn1YRypC-KR6Q2ehj80c4vI/edit?usp=sharing
