### ISSUE TITLE
Research Thesaurus (Descriptives)

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#212]
##### _**Detailed Description**_
Determine the need for a new Descriptives list in place of the existing thesaurus and what is useful for examiners.

##### _**Sprint Goal**_
Support future sprints development work in completion of the examination process.

##### _**Acceptance Criteria**_
- Review with current thesaurus usage and management with Jennifer
- determine what is useful and what improvements could be made.
- determine an approval workflow as only senior examiners can mange the thesaurus

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Directional research conducted with Jennifer.  
It would be beneficial if the current thesaurus was replaced with a descriptive list that can have a group with a group title and also have the ability to add additional categories to understand the possible usages of  a particular word.  As well only senior examiners should be able to approve words into the Descriptives List.

The workflow we discussed is as follows:
Name Parts words are displayed on the examination screen.  The examiner flags new words to be added to the Descriptves List.  These words are added with a state of Submitted.
The senior examiner has the ability to get a list fo words that ahve been submitted and add them to a new or exiting group as well as tage the word with zero, one or many categories.  
The senior examiner also has teh ability to add or delete categoies.

A group can have as little as one word but cannot 0 words.
A word does not require a category.
Group titles can be edited.
Groups can be deleted that have no words.
Words can be deleted if they have no groups or categories.
Categories can be deleted if they have no words.

**Comment by LJTrent** [comment]
@JohnamLane 

Hi John, You mentioned on Friday that you were going to do some research on the structure and how it is currently used.  I had already spoken to Jennifer on some potential opportunities and have record them here.    I have also re-assigned this to you so you can continue with the research.  Thanks, L

**Comment by LJTrent** [comment]
@JohnamLane  I think you need to attach your powerpoint to this issue.  I believe we still need to understand which letters are replaced like K -> C, when double letters are removed and what the significance is of doing that.  What we need to know ->was this done simply because of the technology or is there a business reason for doing it.  If it is just for technology than we have an opportunity to change how we do it. I believe it is important to understand this before next Wednesday so we can plan appropriately. Is this something you wish to take on?

**Comment by JohnamLane** [comment]
Here's the short presentation on the current state search. I need to ask Omid for more detail about the consonant swapping and the double vowel removal stuff.

[NE MANUAL SEARCHES.pptx](https://github.com/bcgov/name-examination/files/1825618/NE.MANUAL.SEARCHES.pptx)

**Comment by JohnamLane** [comment]
Last details coming tomorrow. I will share with team tomorrow.
