### ISSUE TITLE
Example NRs Accepted or Rejected

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#222]
##### _**Detailed Description**_
We would like to see a report of past Name Requests, if they were accepted or rejected, and reasons why (if possible), to reference and test against. 

##### _**Sprint Goal**_
Support developer's building the Get Related Names component in the sprint.

##### _**Acceptance Criteria**_
A report of Name Requests with details made available to the team.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [ ] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@juliainkster Posted samples for approved, rejected and conditionally-approved NRs on Sharepoint. If you need more fields than I have included please let me know.  This is data in namesu which is derived from production data.
