### ISSUE TITLE
Display Name History

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#234]
As an examiner I want the system to find previously decided (approved/rejected) name requests that have the exact match or are similar to the name choice under examination so that I can determine if this is a re-submission or if it is an unrelated NR.

##### BDD Pseudo-Code (GIVEN "context" ... AND "more context" ... WHEN "this action occurs" ... THEN ..."result")

GIVEN the NR is the current one the examiner is working on and it is has a status="IN PROGRESS" 
WHEN the Name Choice is prepared for searching
THEN determine if there is existing approved and rejected name requests that have the same name.

##### _**Acceptance Criteria**_
-use the prepared name choice words to perform the search
-search against the existing approved and rejected name requests  that have not been consumed with the exact name minus designation
-display all names that are the same in the previous NRs section of the examination screen.
-name requests should include the following info:
Name (NR url to open in a new tab), NR #, Request Type, Status, Expiry Date
-currently the examiner types a C beside the conflict.
 
##### _**Definition of Done**_
- [x] Analysis/Design 
- [x] DB 
- [x] UI 
- [ ] Integration Points
- [x] Logic
- [ ] Test Script

##### _**Issue Checklist**_
- [x] BDD Pseudo-Code  
- [x] Estimate  
- [x] Priority Label  
- [x] Story Label  
- [x] Linked EPIC

**Comment by JohnamLane** [comment]
Business Rules complete:
https://sbc.gov.bc.ca/bcregistries/Names Examination/Issue 411 - History Recipe Step - Business Rules.docx
