### ISSUE TITLE
Prepare Name Choice Words for Subsequent Searching

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#235]
#### **Story**
As an examiner I want the system to prepare the words for searching so that I do not have to manually insert words, wildcards or truncations to perform subsequent searches to determine if the name choice is in conflict with an existing corporate name or cause confusion between the companies in the market place.

##### BDD Pseudo-Code (GIVEN "context" ... AND "more context" ... WHEN "this action occurs" ... THEN ..."result")
GIVEN the NR the examiner is working on and it has a status="IN PROGRESS"
WHEN a name choice is selected
THEN
prepare the name choice words for subsequent searching.

##### _**Accepted Criteria **_
All name choice words have been evaluated and turned into the words that will be used for identification of the name parts (distinctive and descriptive).

##### _**Logic **_
Currently the examiner presses PF5 beside the name choice to begin auto-searching. We could also do this.
1) Check for conjunctions after the first word including for,and, nor, but, or, yet, so  Hal's BCBuilding World and Emporium>HAL's BCBuilding World Emporium
2) Remove any punctuation or special characters including: ; @ , ! # . ' + * & % $ ~    ->Hals BCBuilding World Emporium
3) Convert to lowercase -> HALS BCBUILDING WORLD EMPORIUM
4) Look for restricted words embedded in name words:
     scan through all restricted words  (restword table) to find a match within each name word:
	    for each restword.wordfras
		  is BC embedded in HALS - no
		   is BC embedded in BCBUILDING - match *** restcndid=119, 
                   wordfras='BC' (BC is embedded)
								   
 update name search words to separate BC from BUILDING -> HALS BC BUILDING WORLD EMPORIUM
								is BC embedded in WORLD - no match
								is BC embedded in EMPORIUM - no match
							  
		next restcndid, wordfras from restword
		 end loop
							  
5) Find root words for all descriptives   HALS BC BUILDING WORLD EMPORIUM - >HALS BC BUILD WORLD EMPORIUM

##### _**Issue Checklist**_ 
- [ ] BDD Pseudo-Code 
- [ ] Estimate  
- [x] Priority Label  
- [x] Story Label 
- [x] Linked EPIC

##### _**Definition of Done**_
- [x] Analysis/Design 
- [ ] DB 
- [ ] UI 
- [ ] Integration Points
- [x] Logic
- [ ] Test Script

**Comment by rarmitag** [comment]
This one is still in new because we have a meeting scheduled for Tuesday to see if John Jordan's group has anything we can use.
