### ISSUE TITLE
Display Base Name Request Details -  Front-End

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#238]
##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [ ] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by LJTrent** [comment]
@rarmitag   Hi,  I found your task.  We had moved it to sprint 3.  Will it be completed this sprint?

**Comment by rarmitag** [comment]
Mostly, but not entirely.

**Comment by LJTrent** [comment]
@rarmitag  Ok.  I will leave it in sprint  3 then.  Thanks.
