### ISSUE TITLE
Identify and Display Restricted Words - Data

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#247]
##### _**Detailed Description**_
Get the tables set up in the database that are required to determine restricted words. 

##### _**Acceptance Criteria**_
Tables, queries and test data are built and ready to be consumed by the web service.

The function: get_restricted_words(p_name_choice)  returns a string with a list of restricted words that were found in the name choice.  The format of the string returned is word_id:212word_id243 ...

Use this query to extract all data elements for each word found in the api and return as a json file.

select rw.word_id, rw.word_phrase, rc.cnd_text, rc.allow_use, rc.consent_required, rc.consenting_body, rc.instructions
from restricted_word rw
inner join restricted_word_condition rwc ON rwc.word_id = rw.word_id
inner join restricted_condition rc ON rwc.cnd_id = rc.cnd_id AND rwc.word_id = rw.word_id 
where rw.word_id = <word_id>; 

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [ ] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by katiemcgoff** [comment]
Note to self from discussion with Julia: consider how to convert from all uppercase to be more readable by requester, especially when getting correspondence re. consent requirements. Also nice-to-have for examiners for all data coming from mainframe.
