### ISSUE TITLE
Display Base Name Request Details -  BDD

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#263]
##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [ ] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by JohnamLane** [comment]
I have made an initial commit to the repo. Next, I need to handle authentication so that I can make it to the NR details screen and draft the real test.

**Comment by JohnamLane** [comment]
I will close this now and create a new task once authentication is implemented along with the pipeline.
