### ISSUE TITLE
Complete Display Base Name Request Details -  Front-End

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#316]
##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [x] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by juliainkster** [comment]
https://docs.google.com/presentation/d/1GKjjiX0Nv1HlkCuxv7GKuq2gEvjP0w56z3XLW5x95uU/edit?usp=sharing


See slides 20 through 26 for UI layouts and examples of different scenarios.
