### ISSUE TITLE
Finalize UI screens for development

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#375]
----
----
#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] User Story :one:
- [ ] Priority Label :one:
- [ ] Story Label :one:
- [ ] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] BDD Pseudo-Code :two:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Scenario Label :one:
- [ ] Assignee :one:
- [ ] Linked Story :one:
----
----
##### _**Detailed Description**_
Refine UI screens for each element identified in this document:
https://sbc.gov.bc.ca/bcregistries/Names%20Examination/NE-UIelement-tracking.xlsx 

In NE-UI-Sprint4: https://docs.google.com/presentation/d/1-_mfpPl6RL8kBlugBl0V-0e3g7gVYPF2IYSmNjob4EQ/edit?usp=sharing 

And document details about functionality not captured in mock-ups. 

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@juliainkster  Hi, I see this story is a 21.  You may want to keep this story but create UI tasks specifically for the stories that have to get done this sprint and  do the estimates on those specific tasks so it is more manageable.  Then I would remove the estimates form this task.  You could keep it as the parent task and attach the detailed ones with the estimates to it or retire this task and add the individual UI tasks to the specific stories.  We can chat about this before the stand-up if you like.
