### ISSUE TITLE
Enhance Display Base Name Request Details  -  Front-End

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#387]
##### _**Detailed Description**_
Enhance the NR details display by including all UI mock-up style and appearance.

##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [x] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by JohnamLane** [comment]
Business Rules Document:
https://sbc.gov.bc.ca/bcregistries/Names Examination/Issue 406 Display Base Name Request Details - Business Rules.docx
