### ISSUE TITLE
Update NR Details in NRO - Back End

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#424]
##### _**Detailed Description**_
Send all edited NR submission details back to oracle names/NRO database.

##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [ ] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [x] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by LJTrent** [comment]
@katiemcgoff  This isnt working but I think I know the reason.  I just realized the database link  for addresses I think is a read-only link whch of cousre wont allow you to update the address table.  The Update is generating a 400 error.  I think you may have to connect to the db direcrtly to do the insert to the address table but we will need to confirm that with the DBAs hopefully on Monday. Not sure how NRO does it today maybe Walter knows.

**Comment by WalterMoar** [comment]
No, there's no link from the names databases to global. NRO and NRO-WS use separate datasources for connections to the global database, and they connect as the address schema for addresses. In other words, we need another foreign data wrapper.

**Comment by LJTrent** [comment]
I don't believe the nro_updater is using any of the wrappers -just a straight database connection so it will mean we need another oracle database connection for global, addressdb rather than a wrapper.

**Comment by WalterMoar** [comment]
No, there's no link from the names databases to global. NRO and NRO-WS use separate datasources for connections to the global database, and they connect as the address schema for addresses.

Can the NRO updater handle another data source?

**Comment by LJTrent** [comment]
@katiemcgoff 
In dev, NR 0472829,  udpate dthe applicant middle name which should only update request_party and got a 400.

![image](https://user-images.githubusercontent.com/35615843/46026446-361d7280-c0a0-11e8-8362-8974c545e420.png)

**Comment by LJTrent** [comment]
@katiemcgoff 
in dev, NR 4745075.  Updated the NWPTA dates for AB and SK and fot a 400 error.
![image](https://user-images.githubusercontent.com/35615843/46027261-49314200-c0a2-11e8-994e-9cb296434e13.png)

**Comment by katiemcgoff** [comment]
@LJTrent this is ready for testing again, it's got all its appropriate permissions.

**Comment by LJTrent** [comment]
@katiemcgoff  
Looking good  request_party and address stuff updated properly in oracle and show in the namex UI
Name choice is updated in oracle and shows n the UI.  There is one small issue with the name_instance update.  The new row does not capture the designation. NRO puts the company designation in the designation field and we only include it in the name.  
Eg. NR 0472829
![image](https://user-images.githubusercontent.com/35615843/46115913-2db35d80-c1ae-11e8-8b7b-e0534fe5938d.png)

**Comment by LJTrent** [comment]
@katiemcgoff 
Also the comment did not go back to oracle,.
![image](https://user-images.githubusercontent.com/35615843/46115981-85ea5f80-c1ae-11e8-88d1-b8a71cc32e98.png)

![image](https://user-images.githubusercontent.com/35615843/46115996-939fe500-c1ae-11e8-8e24-ec6cff6a5069.png)

**Comment by LJTrent** [comment]
NWPTA edit caused a 400 error.
NR 2804551.

I suspect the the insert/update permissions were not completed for namex for the partner_name_system table.  I will check with David Roberts.

**Comment by LJTrent** [comment]
@katiemcgoff 
Whne the state of an NR is INPROGRESS you can eidt all of the nr fields except NWPTA.  NWPTA should also be editable.

eg. in dev, NR 2023155.  Login as names-examiner.

![image](https://user-images.githubusercontent.com/35615843/46171928-dc12dd80-c256-11e8-9491-6fd4a14c093e.png)

**Comment by LJTrent** [comment]
@katiemcgoff  
Please promote to test.
