### ISSUE TITLE
Select Decision Reasons - Back End

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#440]
##### _**Detailed Description**_
Includes API test

##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [ ] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by katiemcgoff** [comment]
From Lorna: 

**Decision Text**

> Decision text is updated in the name_state table in the state_comment field is VARCHAR2(1000).  The decision comes across as p_choice1 for name choice 1, p_choice2 for name choice 2 and p_choice3 for name choice 2.  The format that is expected by the names examination proc is:
> `
> 'state'****<decisions text>
> `
> eg:
> `
> A****this is the decision text 
> `
> 
> up to 1000 characters that should be formatted for client notifications including CR/LF. 
> eg:
> `
> A****ALLOWED FOR PROPRIETORSHIP/PARTNERSHIP NAME ONLY
> `
> `
> R"***** REQUIRE DISTINCTIVE, NONDESCRIPTIVE FIRST WORD OR PREFIX *E.G. PERSON'S NAME, INITIALS, GEOGRAPHIC LOCATION, ETC.*               REQUIRE DESCRIPTIVE SECOND WORD OR PHRASE *               E.G. CONSTRUCTION, GARDENING, INVESTMENTS, HOLDINGS, ETC..  
> `
> 
> 

**Conflicts**

> Also, name_rule table is updated for rejections and can list up to three conflicts (NRs and/or Corporations) per name choice.  The fields that are updated in name_rule are"
> - CONF_NUMBER VARCHAR2(10) which is the NR # or corp num and 
> - the conf_name which is the name VARCHAR2(150)(corp name or NR name choice).  
> 
> The conflict_names that are passed back to NRO name_examination proc must be formatted a particular way.  eg. for name choice 1, "conflict11NR 9174764***STEEPHILL COOPERATIVE. For name choice 1, second conflict->"conflict12NR 9174564***STEEPHILLS COOPERATIVE ...They are passed to name_exmaintion proc as p_confname1A, 1B, 1C, p_confname2A, 2B, 2C, p_confname3A, 3B, 3C
> 

**Status**

> For Conditionallty  Approved, the name examination proc is expecting a p_consent_flag='Y'.


**For view only**

> Other NR Details to be added, expired date consumption date, consent flag,
> If the consent has already been received then the consent_flag may be set to R (Received) in NRO and the date the consent was received. This allows examiners to look at any NR in any state.  We may want to reflect that in the names details along with expiration date and consumption date.
> I went through all the request types and there additional fields previous NR # and corp num.  Both must be valid when entered.  We can talk about the circumstances and how we want to handle this tomorrow with Thor

**Comment by katiemcgoff** [comment]
Closed in Sprint 7, replaced by #528 in Sprint 8.
