### ISSUE TITLE
Undo Decision - Front End

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#445]
##### _**Detailed Description**_
Add a button that is only visible after an examination has been approved or rejected that allows the examiner to undo a decision.  ~~The system should enforce that a comment is entered by the examiner to document why they are undoing their decision.~~

If undoing during regular examination, only allow undo of most recent decision. If undoing during re-evaluation (ie: reset a furnished NR) allow to cherry-pick individual decision.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
Open questions:
- Kaine/business: undo all name decisions? Ie: lose data re. why say, first name was rejected if the examiner is re-opening to approve the second?
  - OR re-open but leave all name decisions and allow examiner to cherry-pick which name(s) to re-examine?

**Comment by katiemcgoff** [comment]
Closed in Sprint 8, replaced in Sprint 7 by #529.
