### ISSUE TITLE
Undo Decision - Data

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#446]
##### _**Detailed Description**_

Required data that must be updated for the names examination database as well as formatting data for namesp.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment]
**ANY** Examiner can pull back **ANY** '_COMPLETED_' (sub-states => '_Approved_', '_Rejected_', '_Condition_') and move it to '_INPROGRESS_'  to alter it, as long as it has not been sent to **NRO**, or in future '**Furnished**'
-- this will be in place for v1 as discussed with Deb
