### ISSUE TITLE
Create Research Plan Document

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#50]
----
----
##### _**Detailed Description**_
Turn Research plan canvas into a document.

##### _**Acceptance Criteria**_

- Word doc with all of the sections from the Research Plan Canvas, for future reference re: research approach taken for this project
- detail all research activities done to date as well as those planned for future stages

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Complete :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----
#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] User Story :one:
- [ ] Priority Label :one:
- [ ] Story Label :one:
- [ ] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] BDD Pseudo-Code :two:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Scenario Label :one:
- [ ] Assignee :one:
- [ ] Linked Story :one:
----
----

**Comment by LJTrent** [comment]
@megwhetung 
I estimated this as a 2- one day -one person .  Is this something we can do when we look at the journey maps ... next week?

**Comment by LJTrent** [comment]
@megwhetung 
Can you also add some acceptance criteria and a sprint goal.  I haven't added it to sprint 1 yet.  Does it need to be done then? Maybe it can wait?

**Comment by megwhetung** [comment]
@LJTrent I've added some acceptance criteria. I think it could wait until a later sprint.
