### ISSUE TITLE
Feed SOLR changes from NAMES

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#527]
##### _**Detailed Description**_
Continuously update the SOLR index for NAMES as names are approved or rejected:
- update the history core - For the names core we only care about names that have a request_type that have a class_type_cd=CORP
- update the conflicts core (determine how we know when a name is consumed)
The approved names portion of the possible conflicts again we only want the ons that have a request type that is of class_type_cd =CORP.  that eliminates all the sole prop and partnership names.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Updated the Oracle package NAMEX.solr with the code to send messages to Solr. Still needs work but it's a lot easier now. Updated the web service to handle multiple results per NR, and to do a better job of only feeding possible.conflicts what it wants.

**Comment by WalterMoar** [comment]
Big rewrite has been completed, and all the logic has (unfortunately) been moved into the Oracle database. The solr-feeder web service is now a very basic pass-though, but it's a much simpler design with fewer failure points.

**Comment by WalterMoar** [comment]
At 11:30 on 2018-09-15, the Solr cores were synchronized with CUAT and NAMESU. The Solr feeder process is live for both databases, so Solr and the databases should remain in sync. If not, bugs should be opened to determine why they are diverging.

Smoke tested by creating NR 3182749, approving it via the NAMESDB@NAMESU package, and then consuming it with BC0874264.
