### ISSUE TITLE
Feed SOLR changes from REGISTRIES

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#530]
##### _**Detailed Description**_
update the SOLR conflicts core based on changes in the corporate registry.  We only want corps that have a corp class 

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
At 11:30 on 2018-09-15, the Solr cores were synchronized with CUAT and NAMESU. The Solr feeder process is live for both databases, so Solr and the databases should remain in sync. If not, bugs should be opened to determine why they are diverging.

Smoke tested by creating NR 3182749, approving it via the NAMESDB@NAMESU package, and then consuming it with BC0874264.
