### ISSUE TITLE
Automate SOLR Core Data Load

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#541]
##### _**Detailed Description**_
Load data into SOLR cores.

##### _**Acceptance Criteria**_

Definition of Done
 - [ ] Analysis/Design
- [ ] DB
- [ ] UI
 - [ ] Integration Points
 - [ ] Logic
 - [ ] Test Script

##### _**Issue Checklist**_
- [ ] Acceptance Criteria Defined
- [ ] Estimate
- [x] Priority Label
- [x] Task Label 
- [ ] Assignee

**Comment by VarekBoettcher** [comment]
Not complete.  Continued as #577
