### ISSUE TITLE
Edit Priority - Front and Back End

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#550]
##### _**Detailed Description**_

Per Sprint 7 Demo/Review, examiners need to be able to edit priority.

This had been implemented and then removed previously when it was thought that this should not be editable, so this task is to a) find the code and re-implement it, and b) ensure that the API call handles the change correctly.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:

**Comment by LJTrent** [comment]
Priority must be managed from NRo because it carries a fee.  We iwll not implement payment processing in Namex.
