### ISSUE TITLE
Load Federal Trademarks into Solr

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#587]
##### _**Detailed Description**_
Upon receipt of the DVDs containing the federal trademarks data, process them and upload the resultant file to the Names environment.

##### _**Acceptance Criteria**_
- [ ] Raw trademark files processed into single result file ready for upload
- [ ] Upload trademark file to Names environment(s)
- [ ] Perform trademarks data load

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Duplicate of #651 - closing.
