### ISSUE TITLE
Update Synonyms for Solr

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#590]
##### _**Detailed Description**_
Setup a way to update the synonyms that Solr uses in an ongoing basis. in a deployment.

5 Days

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
After much Jetty/JNDI pain, Solr on my desktop is now loading synonyms from postgres (also running on my desktop). I'm in need of credentials on the postgres database in OpenShift. Also, I need to discuss best practices for how to build namex-solr-core. When I'm back in the office on Friday I can start the work on getting this into OpenShift, but it won't happen for this sprint.

**Comment by WalterMoar** [comment]
namex-solr-core has be built with solr-jdbc, Apache db Utils, and the Jetty modules and libraries needed for JNDI.

**Comment by WalterMoar** [comment]
Authentication is finally complete. I'm going to skip authorization for now and take the existence of a username as sufficient proof of authority.

**Comment by WalterMoar** [comment]
Auditing is now complete, and deployed to dev with an updated database. Automatic reloading of the Solr cores is not complete, but that can be done manually. Focus now is to get it into test for the demo on Monday.

**Comment by WalterMoar** [comment]
I finished building the test environment, and it is now ready for the Monday demo. I'll try to complete the automatic core reloading, then this ticket can finally be closed.

**Comment by WalterMoar** [comment]
Automatic core reloading is complete. Also added better validation of the Synonyms Text field to disallow singletons, duplicate values, or embedded spaces.
