### ISSUE TITLE
Add release tag to UI for testing, to refer to with examiners

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#593]
Add release tag to UI for testing, to refer to with examiners.

**Comment by thorwolpert** [comment]
We will conform to PEP 440 -- Version Identification and Dependency Specification
TL;DR
<public version identifier>[+<local version label>]
<public version identifier> == > [N!]N(.N)*[{a|b|rc}N][.postN][.devN]
<local version label> ==> component.<git commit hash>
This will be stored in the top packages version.py and exposed in the __init__.py as __version__ = <public version identifier>[+<local version label>]

For purposes this version.py file will get over-written during the build process with last tag on the branch, component and last commit-hash.
APIs will place this version in the HEADER as meta-data

JavaScript front-end will have this in the next comment

**Comment by LJTrent** [comment]
@thorwolpert  DO we need this to deploy using features, as we discussed so only certain people could test in test

**Comment by LJTrent** [comment]
Done.
