### ISSUE TITLE
move any INPROGRESS Requests to ONHOLD that have been inprogress for more than 30 mins

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#603]
##### _**Detailed Description**_

Confirm 30 mins is the interval wanted.  This has been confirmed with Julia.

Cronjob needs to be setup in openshift to run the sql below. 

SQL: update requests set state_cd='HOLD' where state_cd='INPROGRESS' and last_update < (current_date - interval '30 minutes');

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment]
Should this just blindly run at midnight and switch any Requests still INPROGRESS to HOLD? The other option is to run more often, but move any Requests that has been left INPROGRESS for longer than set time period.

**Comment by Kaineatthelab** [comment]
I think we agreed we can let this run every 30 min and as you suggested we should allow examiners the ability to break in.
