### ISSUE TITLE
Move all "registered" (status) trademarks to top of Trademarks list

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#609]
##### _**Detailed Description**_

Per review with Jennifer 2018-07-06:

Sort order or priority from Solr - trademarks with status "REGISTERED" should be at top of list.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@thorwolpert @katiemcgoff 

The solr api for trademarks will need to use a bq parameter to boost the score of all registered trade marks that match.  here is an example:

http://localhost:8983/solr/trademarks/select?bq=status:%20REGISTERED&defType=edismax&fl=name,status.score&indent=on&mm=75%25&q=*:*&wt=json
