### ISSUE TITLE
Create NRO Trigger

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#633]
##### _**Detailed Description**_
Create an insert trigger on the transaction table using the pseudo code on Slack as a guide.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
The trigger itself, and the corresponding NAMEX package, are complete.

**Comment by WalterMoar** [comment]
Everything behind the trigger for Solr is now complete. I lack privileges to create the Solr update job, but David/Bob can do that tomorrow. Running the job manually works and data is updated in Solr.

**Comment by WalterMoar** [comment]
Trigger completed for Solr. This ticket doesn't specify whether or not the updates of the postgres DB are included, but I'm assuming that's covered off elsewhere.

At 11:30 on 2018-09-15, the Solr cores were synchronized with CUAT and NAMESU. The Solr feeder process is live for both databases, so Solr and the databases should remain in sync. If not, bugs should be opened to determine why they are diverging.

Smoke tested by creating NR 3182749, approving it via the NAMESDB@NAMESU package, and then consuming it with BC0874264.
