### ISSUE TITLE
Get Admin Access on Your Own Computer

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#64]
----
----
##### _**Detailed Description**_
This is required so you can install software  on your machine.  Developers will need it for  a variety of tools and approvers will need GitHub Desktop.

##### _**Sprint Goal**_
Supports the sprint by getting all of tools installed on your desktop that you need.

##### _**Acceptance Criteria**_
-Admin rights to your local machine are working.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:

----
----
#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] User Story :one:
- [ ] Priority Label :one:
- [ ] Story Label :one:
- [ ] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] BDD Pseudo-Code :two:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Scenario Label :one:
- [ ] Assignee :one:
- [ ] Linked Story :one:
----
----

**Comment by JohnamLane** [comment]
Still outstanding:
- Richard A
- Debbie
- Varek
- Kaine
