### ISSUE TITLE
History changes

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#650]
- in details:
  - status
  - comments WITH timestamp and username (see InternalComments.vue for layout)
  - date
  - NR # link (empty link for now)
- in list:
  - indication of accept/reject
- recipe indicator
  - if exact match that was rejected, red X 

@juliainkster set up meeting w. business and Kial to decide what they need in History.

**Comment by Kaineatthelab** [comment]
How does the system work now?
There are 2 messages
Similar name previously rejected
Similar name previously approved

It takes the name in that request and searches the existing name reservations (the request table which is any name request that we have ever had rejected or approved)

It looks like it mimics this already and adds to the submit count, not sure if submit count and the text displaying "this has been applied for 1 time before" is the same logic in the new system?

Currently in Test I see that it brings back a bunch of names that are irrelevant so we need to tweek that. Also still need to get the firm names out of the data.

**Comment by katiemcgoff** [comment]
Functionality re. red message ("previously approved/rejected") moved to new issue #683.
