### ISSUE TITLE
Feed SOLR for Trademarks

### ISSUE THREAD

**Issue by VarekBoettcher** [bcgov/name-examination#651]
##### _**Detailed Description**_
Take the raw federal trademarls xml files form any directory and feed them into the solr core. 

##### _**Acceptance Criteria**_
Pre-processor creates an output file that is consumable by the SOLR trademarks core data load.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [ ] Priority Label :one:
- [x] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Decisions made:
 - use only MarkFeatureCategoryType of "Word".
 - include all MarkCategory types, but add a "category" field to the Solr core.
 - exclude MarkCurrentStatusCategoryType when inactive: 'Application refused', 'Application withdrawn', 'Registration cancelled', 'Registration surrendered'.

**Comment by WalterMoar** [comment]
847753 trademarks loaded into test. The scripts are in github in namex/solr/trademarks, and the artifacts (parse log, parse output, and list of missing descriptions) are in N:\BCAP2\6450 Projects\20-Mainframe Migration\Names Examination\trademarks.

**Comment by LJTrent** [comment]
trademarks core has 847753 records in dev, test and prod.
