### ISSUE TITLE
Manual Search changes

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#658]
Per feedback from Julia.

@juliainkster please complete.

**Comment by thorwolpert** [comment]
Are you saying a "+" sign triggers the manual search? Is that part of a keystroke combo, because I thought they had to put "+" signs in front of words they wanted to emphasize in the search

**Comment by juliainkster** [comment]
Oops!  Thanks for pointing that out. My comments included characters used for formatting here apparently. 

Shift plus Enter to submit the manual search
Shift plus C to cancel
