### ISSUE TITLE
Add e2e Selenium Tests to the pipeline

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#661]
1. set up locally
2. write first selenium test
3. get selenium running in pipeline

Estimate: 2 days (each person)

**Comment by ericminio** [comment]
I suggest we remove this one and make it happen in https://github.com/bcgov/name-examination/issues/987

**Comment by thorwolpert** [comment]
as a full e2e (at a minimum smoke test) it doesn't fit with the 987 (fake out authentication) tests. e2e will test out all of the integrations and configs to ensure a working system.

**Comment by ericminio** [comment]
Thank you @thorwolpert

I understand the intention is to "ensure a working system".

Will you share more details about your vision for this test?
- against which environment?
- using which credentials?
- covering which feature?

Thanks
