### ISSUE TITLE
Automate SOLR Config Maps

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#698]
##### _**Detailed Description**_

Automate the loading of the config maps required by the SOLR  as part of the deployment.

5 Days

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
The work on #590 has laid the foundation for this to be completed. We will be able to replace the three data config files in the Config Maps with a single file that defines the three database connections (synonyms, FDW for corporations, and FDW for names).

**Comment by WalterMoar** [comment]
Moved into test as part of the work for #590.  Old config maps have been removed and new config map added - the new map only contains the database locations, so it is unlikely to change. We can look at moving it into the build at some point, but it is a very low priority.
