### ISSUE TITLE
When user is timed out, force them to log in again

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#716]
##### _**Detailed Description**_
Currently when user is timed out they just get 401 errors from API calls but nothing happens on the front end. Change this to actually handle 401 errors - send user back to login screen.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@rarmitag  Tested in dev.  After 30 minutes of inactivity on the examination screen,  when you select only name history you get a 401 error on the screen and it turns logout to login on the top navgation bar but it does not take you to the login page and you still get this 401 error not a message that stats you have been logged out.
