### ISSUE TITLE
DB Backup and Recovery (namex api)

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#725]
- [] create backups
- [] sftp backups to Oracle server ?
- [] test recovery
- [] test removing of pods for HA
- SOLR postgres db

**Comment by katiemcgoff** [comment]
Msg'd Jeff Kelly Monday - waiting on response expected Tuesday.

**Comment by katiemcgoff** [comment]
Plan while waiting on permanent solution - get permanent storage provisioned, create a cron job to pg_dump to it. 

Also need to document steps to restore backup if necessary.

**Comment by katiemcgoff** [comment]
From Clecio:

>Cron Jobs:
>https://github.com/bcgov/gwells/blob/master/openshift/cronjobs.json
>https://github.com/bcgov/gwells/tree/master/database
>
>It sounds like some templates are missing/outdated, I’ve asked the team to update them.

**Comment by LJTrent** [comment]
Need to test upgrade and roll it out to test and prod.

**Comment by LJTrent** [comment]
@thorwolpert  Hi,   Has this been completed yet?
