### ISSUE TITLE
Handle timezones in front and back end

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#730]
##### _**Detailed Description**_
Our postgres database stores dates in UTC and per Thor, that is good:

>gov't generally uses UTC, as they have DCs in Kamloops (PST), Calgary (MDT), and other cloud sites. Generally it is made local during display to the user. UTC also doesn't do daylight savings, so there is no roll forward / back issues.

So we need to a) change front-end to display in user's browser timezone) and b) change NRO Sync (nro_sync.py) to check for latest changes in UTC time, rather than how it currently checks in current server time, aka 8 hours behind UTC time.

Note: UTC is "Universal Time Coordinated", which is equivalent to GMT ("Greenwich Mean Time", for Greenwich UK) which is the starting point for all other timezones, and does not change with daylight savings time. Our timezones are PST ("Pacific Standard Time") which is 8 hours behind GMT, and PDT ("Pacific Daylight Time") during daylight savings which is 7 hours behind GMT.

##### _**Acceptance Criteria**_
- When logged in as a user in Victoria, the date/time on screen (submitted, expiry, consumed date) is local to Victoria.
- When logged in as a user in Calgary, the date/time is local to Calgary.
- When NRO Sync processes records, it gets latest changed records (within its 10 or 20 minute threshold); it does NOT wait 8 hours to process records.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment]
I think nro_update/sync was always using the databases timezone. In any case the current updater is using now() as a db call, which is taking the database timezone that it executes in, and the servers are set to UTC.

**Comment by JohnamLane** [comment]
@kialj876 Please review NR 1278501 in DEV. It was created around 12PM today, but the timestamp from the search screen shows as 4:54 AM

**Comment by LJTrent** [comment]
@kialj876  Hi, ready to promote to TEST.  Please move to Acceptance Test when it has been deployed.  Thx. L
