### ISSUE TITLE
Quick Approve/Reject buttons show when "Undo Descision" is attached to 1st choice and 2nd/3rd choices are blank

### ISSUE THREAD

**Issue by rarmitag** [bcgov/name-examination#756]
To reproduce:
- find an NR with only one name, such as NR 655711.
- if closed, re-open. If open, make decision on the one name, then re-open.

Expected results:
- The one name will have undo button (as of time of writing these details) and decision buttons ("Decision", "Quick Approve", the two quick reject buttons) will not be displayed.

Actual results:
- Those buttons are displayed.

**Comment by katiemcgoff** [comment]
No longer an issue due to changes in #777 .
