### ISSUE TITLE
Completing a Single Name NR

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#761]
##### _**Detailed Description**_

When a single name NR is Approved or Rejected.  The Undo Decision and Re-Open buttons are not displayed.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
Seems to have been resolved by fix for #777 .

Also, in logged bug, only Re-open button would be displayed - Undo Decision button should not be displayed in this scenario.
