### ISSUE TITLE
Solr: don't allow uppercase letters in synonyms

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#775]
##### _**Detailed Description**_

The solr-admin-app currently does not restrict the characters that can be used in synonyms. This needs to be changed to prevent accidental input of characters that could give unexpected search results.

The characters should most likely be limited to a-z (lowercase only), 0-9, and space.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar  Yes.  It is reasonable.
