### ISSUE TITLE
When re-opening a request, all the decision data should be cleared.

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#777]
##### _**Detailed Description**_
When re-opening a request all the decision data should be cleared - decision (A/C/R), comment, conflicts, customer message.

Per request by examiners. 

This is for the RE-OPEN functionality. Matches functionality of RESET.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@katiemcgoff  There seems to be an new issue .  I t appears to only happen when you RE-Open an NR. The workflow I used, is Select an NR that was Approved from the search screen, re-open it which is working as expected, put it on hold. go back to the search screen, select it and load it.  Then the manual search bar is empy.  This is the bug.  I tried putting NRs back and forth on hold and thsi seem sto only be happening when there was a re-open.
