### ISSUE TITLE
Solr: Update managed-schemas

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#783]
##### _**Detailed Description**_

Update the Solr managed schemas for all three cores:
- The index SnowballPorterFilter has removed protected="protwords.txt".
- The index SynonymGraphFilter has been removed.
- The index FlattenGraphFilter has been removed.
- The query SnowballPorterFilter has removed protected="protwords.txt".

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar  The managed-schema looks good.  The flatten goes with the synonyms.  Synonyms were removed from the index analyzer so the flatten was too.  The query analyzer has both the synonyms and the flatten so it all looks good to me.
