### ISSUE TITLE
Detach Internal Comments from NR Details edit functionality

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#785]
There is a business case for a user to enter internal comments regardless of the rules/logic around editing NR Details. 

From meeting w. Lorna, Kaine, Katie, Kial 2018-08-21:
- upon saving, send changes back to NRO
-- might be part of regular "Edit NR" functionality already

Acceptance Criteria:
- User can add internal comments at any point (state, ownership) in the lifecycle of an NR. 
- Adding a comment does not change the NR's state or ownership.

**Comment by LJTrent** [comment]
Completed as part of phase 1 code with us.
