### ISSUE TITLE
Update SOLR Configs with New FD Wrapper

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#790]
##### _**Detailed Description**_
Once the new  FD wrappers have been deployed after the view name changes in oracle and the api changes have been completed,  the solr-data-config.xml files will need to be updated and solr redeployed.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
FDWs have been redeployed, but the NAMEX_ prefix still exists on the views. Blocked until the view names are corrected.

**Comment by LJTrent** [comment]
@WalterMoar  Hi, Just looked at these in openshift.  The fdw deployments still point to NAMESDB instead of NAMEX that is why you still see the view prefixes as well it looks like the pull request for kial's changes to the view names have not been accepted yet and merge into master.

**Comment by WalterMoar** [comment]
Ready for code review.
