### ISSUE TITLE
Add an + Symbol to the First Word in a Name for SOLR Searching 

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#792]
##### _**Detailed Description**_

Add a + sign to the first word and display that in the manual search when a name choice is in focus(selected).  Pass this to solr on the search so it will need to be escaped properly.

PS Richard it is back to a + sign:)

##### _**Acceptance Criteria**_
The + sign is visible in the manual search box and passed to the SOLR API.  As well the user can take it out of the manual search and when the reset the manual search is selected it should be put back in.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by Kaineatthelab** [comment]
I changed it back to + as we should see how it works with + first. The stemming would make sense to keep on the distinctive , for example if it is Canadian we would also want Canada etc...
