### ISSUE TITLE
Solr: restore FlattenGraphFilter for indexing

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#803]
##### _**Detailed Description**_

Update the three Solr managed schema files to restore the FlattenGraphFilter for text_en_splitting indexing. According to the Solr reference guide for the Word Delimiter Graph Filter (p192): "If you use this filter during indexing, you must follow it with a Flatten Graph Filter".

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Hi Lorna - thoughts on this? The flatten filter was removed in the last change, but according to the docs it's needed. Not sure what the implications are of not having it.

**Comment by LJTrent** [comment]
Hi,

Yes it is required and it should not have been removed.  The synonyms filter requires it. I don’t remember why bu tit needs to be put back wherever there is a synonyms filter.

Thx.
L

**Comment by LJTrent** [comment]
@WalterMoar   This is in Dev but has not been pushed to TEST?

**Comment by LJTrent** [comment]
In dev but not in TEST
