### ISSUE TITLE
Solr is maxing memory and compute on dataimport

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#819]
##### _**Detailed Description**_

It was noticed that performance is degraded when Solr *dataimport* calls are made to reload the cores. During monitoring of the most recent dataimports, it was noticed that the Solr pods are pegged at maximum memory (1Gi) and compute (250mcore) for the duration of the loads. Note that with Solr being a Java application, the lack of memory could be causing massive GC time.

Determine the maximum memory and compute we can configure, and try the dataimport to see if there is an upper bound.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Bumped the memory to 1500 mcores in dev and test, and performance is much better. Solr is not hitting either limit on dataimport, but for querying this much compute is not needed.

**Comment by LJTrent** [comment]
@WalterMoar  not sure how I am to verify this?.  Any ideas?

**Comment by LJTrent** [comment]
@WalterMoar  sorl in both dev and test says it is set to 100-250 mcores.  Is it suppose to be or should it be 1500 as per the comment in this ticket?

**Comment by WalterMoar** [comment]
Hmm, that's interesting. I wonder if I recreated the deployments for some reason and overwrote the settings in OpenShift. It could also explain why it took so long to load the trademarks.

I'll take another look at this, and also make sure that production is ready for tomorrow's core loads.

**Comment by WalterMoar** [comment]
Actually, maybe it's OK as-is. If we are going to do a dataimport we bump it up to 1500 mcores via the web UI., and after the dataimport we set it back. We don't need to extra capacity for day to day running of the pod, so no point in having the upper limit if we never use it. If for some reason we forget to reset it after the dataimport, a subsequent redeploy may be all it takes to knock it back down.
