### ISSUE TITLE
Loading an NR from search screen does not show decision (or reason) for some states

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#821]
##### _**Detailed Description**_
Loading an NR from search screen does not show decision (or reason) when NR is Expired, Completed, Expired, or Historical. 

See screen for example of a Completed NR.  Would expect decision.![Completed-State.PNG](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/e3e9aaad-0e3c-4640-bb15-58928dbcd3aa)

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
This has been resolved in dev and test in another issue.
