### ISSUE TITLE
Solr: create a dataimport view for each core

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#823]
##### _**Detailed Description**_

The current Solr setup has a single view COMPLETED_NR_VW that is used for dataimports for both the names and possible.conflicts cores. The two cores use different fields from the view. Also, the conflicts core has a number of restrictions on what is to be included in the results.

Having a single view isn't so bad for Solr dataimports, but the solr-feeder web service also needs to call these views to get data. It will be much more complicated to implements the possible.conflicts core restrictions in Python code. Also, having the logic in two places makes it more complicated to make changes to the restrictions on the returned data.

Suggest that we have a view for each core, tailored to that core. This isolates the logic in a single place, and will make the solr-feeder much simpler.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Hi Lorna - thoughts on this? I think it would be better in the long run, and will make the solr-feeder much simpler to build.

**Comment by WalterMoar** [comment]
Created SOLR_DATAIMPORT_CONFLICTS_VW and SOLR_DATAIMPORT_NAMES_VW. Updated the solr-feeder to use the new views.

**Comment by WalterMoar** [comment]
Done for names, but keeping this open to do the corporations view in the same way.

**Comment by WalterMoar** [comment]
Done for corporations as well. Did a dataimport for names and possible.conflicts cores in both dev and test. Ran optimize or core reloads so that all core statuses are green.

**Comment by LJTrent** [comment]
Checked solr-data-config and the views in both dev and test.
