### ISSUE TITLE
Solr: synchronize configuration files

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#825]
##### _**Detailed Description**_

The fields in the managed-schema files are not in sync with what is in the solr-data-import.xml files. These have diverged over time and should be brought back in line.

name core:
 - solr-data-config.xml: change the pk to be id, not name_instance_id.
 - managed-schema: order the fields to match what's in solr-data-config.xml to make it easier to check correctness. Remove unnecessary fields. Change the uniqueKey to "id".

possible.conflicts core:
 - managed-schema: order the fields to match what's in solr-data-config.xml to make it easier to check correctness. Remove unnecessary fields.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
checked solr-data-import, manage-schema configs and views in NAMEX.  Checked both dev and test.
