### ISSUE TITLE
Add to Restricted Words

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#826]
##### _**Detailed Description**_
Word: Chamber of Commerce  
Consenting Body: Board of Trade and Chamber of Commerce:
Allow_use: Y
Conset_Required: Y
Examiner instructions:
Client instructions: Use of thi sterm requires written consent from the BC Chamber of Commerce at 604- 638-8110 or email vlitwin@bcchamber.org. 

Update to an existing word SASKATCHEWAN.
Word: Saskatchewan
Consenting Body: Province of Saskatchewan
Allow_use: Y
Conset_Required: Y
Examiner instructions:
Client instructions: Use of this term requires written consent from the Province of Saskatchewan at publicregistryadmin@gov.sk.ca.  Please scan your consent to bcregistries@gov.bc.ca.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by JohnamLane** [comment]
@kialj876 The 'Client instructions' for Saskatchewan need to be updated.

**Comment by katiemcgoff** [comment]
check for duplicate saskatchewan

**Comment by katiemcgoff** [comment]
@JohnamLane ready for review in dev and test.
