### ISSUE TITLE
Clean up COLIN_MGR_UAT and NAMESDB schemas

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#831]
##### _**Detailed Description**_

During development a bunch of object (views, synonyms, more?) were added to the CUAT.COLIN_MGR_UAT and NAMESU.NAMESDB schemas. The Foreign Data Wrappers now point to the NAMEX schema in both databases, so the chances of us accidentally needing these objects is slim. However, for the sake of completeness we need to put things back the way they were.

Once we are done, we can get David Roberts to compare CUAT/CPRD and NAMESU/NAMESP to make sure we didn't miss anything.

CUAT.COLIN_MGR_UAT: every view that starts with NAMEX_, plus any broken/unnecessary synonyms.

NAMESU.NAMESDB: every view that starts with NAMEX_, plus any broken/unnecessary synonyms.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Hello everyone - does this make sense? If no objects I think we should get this done ASAP, so that if there are still dependencies we find them now as opposed to when we go to production.

Should we recreate the FDWs for the sake of completeness/paranoia?

**Comment by WalterMoar** [comment]
Changing this to a "2" as the repository is very out of date with what's actually in the DB.

**Comment by LJTrent** [comment]
@WalterMoar NAME_EXAM schema in namesu still needs to be dropped but I think only David can do that.
