### ISSUE TITLE
bug - name examination screen showing/breaking on cancelled, expired, and historical nrs

### ISSUE THREAD

**Issue by kialj876** [bcgov/name-examination#837]
Hide examination screen for these - same as other 'completed' nrs

**Comment by LJTrent** [comment]
@kialj876 

Its working great except for a couple of issues:

1) the manual search shows +undefined (should just be blank)
2) Conflicts list and detail shows the last one that was loaded. it does not reset it to blank.
![image](https://user-images.githubusercontent.com/35615843/45315085-46522100-b4e8-11e8-9f00-345516fbe688.png)
