### ISSUE TITLE
NRO Updater Not Saving Decision in NAMES for Conditionally Approved NRs

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#855]
-#### **Task** (Use for Work not Directly related to a Story but supports the Sprint Goals)
##### _**Detailed Description**_
Conditionally approved NRs do not set the name_state to C in namesu.  The name_examination proc is expecting A ffor the name status and consent_flag=Y.

Eg. is NR 8308391.  name state=A after the updater runs and consent has not entry for the request_id.  The examination proc dos that as well.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment]
Currently running in TEST, as there is no DEV environment to check this in.

**Comment by JohnamLane** [comment]
Testing has passed so far. Here is what I have tested:
NR 3987600 - quick approved with no request or name comments. The REQUEST_STATE and NAME_STATE updated as expected.

NR 0413629 - Added 2 rejection reasons and they appeared in the NAME_STATE.STATE_COMMENT column. 3rd name choice didn't have a comment so STATE_COMMENT is blank - pass

NR 1927554 - was DRAFT, then changes to H when I hit examine. Rejected with comments for all 3 and they show in NAME_STATE.STATE_COMMENT

NR 0398791 - Reject first name with examiner and client comment. Then add REQUEST_STATE.STATE_COMMENT (Duplicate request) via NRO as cancellation reason.

**Comment by JohnamLane** [comment]
name_state.name_state_type_cd should be set to 'C' when a name is conditionally approved.
NR 2691393 was conditionally approved in Test, but shows as "A" in NAMESU

**Comment by thorwolpert** [comment]
Not an nro_updater issue, it's an extractor.

**Comment by LJTrent** [comment]
Rejected tested with multiple names, one conflict each and one trademark each and decision text and examiner comments for each.  All tables updated as expected in namesu.

**Comment by LJTrent** [comment]
@thorwolpert Tested with NR 7130790, set to conditional, nro updater ran and set the  furnished=Y in namex but did not do any inserts to any tables in namesu.  Looks like it just dropped all the way through the proc.  I checked the application_log table and nothing was written.  It doesn't look like the name_examination proc is even being called. I double-checked and it is expecting p_status='A' and p_consent_flag='Y'

**Comment by thorwolpert** [comment]
Here's what's being sent:
 nr:NR 7130790; p_status: A; expiry_dt:20181117; consent:Y; examiner:ltrent
So something else must be amiss. Will start looking into it.

**Comment by thorwolpert** [comment]
@LJTrent are you looking in namest.bcgov now? it was switched recently.
