### ISSUE TITLE
Condition & Trademark step details pane does not refresh when new manual search is completed

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#866]
##### _**Detailed Description**_
Steps to reproduce:
1) Bring up a name and let autoexamine take place
2) click into the Condition recipe step
3) edit the manual search term and run the search (e.g. add "Doctor")

Result:
The state/colour of the recipe step will update, but the contents pane won't be filled in.
Clicking up the Conflicts step, then back into the Condition step results in the details being populated.
![image](https://user-images.githubusercontent.com/35740635/45512148-c4663000-b753-11e8-9e89-d99fe8d0dd5c.png)

Note:  This issue also occurs on the Trademark step

##### _**Acceptance Criteria**_
The details pane of the recipe step should populate based on the latest manual search that was completed.

**Comment by JohnamLane** [comment]
PASS:
Tested running a new manual search while the Condition step was highlighted and while the Trademark step was highlighted - both updated as expected.

**Comment by juliainkster** [comment]
When trademark word is removed, the trademark list should be refreshed/cleared. 

In this screenshot Apple is still being returned but it is not in the search. 

![image.png](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/f9bce318-c528-45c2-954d-fb22857e02a4)

**Comment by JohnamLane** [comment]
@juliainkster when you get a moment can you add your steps to reproduce? I bet you are on to something but I can't get the same results.

**Comment by juliainkster** [comment]
Oh shoot, I was in test still.  Since dev is working fine we can close. It's a bit confusing that they are working differently. 

1. Examining BCAB POWERLINE LP - no trademarks
2.  Want to look for POWER trademarks so enter POWER into the search field
3. System finds trademarks
4. Click x to clear and APPLE results remain. Recipe indicator changes to checkmark.
