### ISSUE TITLE
Reset from Rejected

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#867]
Test with clean data. 

Scenario:

Loading a REJECTED name from the search screen.

Name has APPROVED style and Status: REJECTED (see screenshot)
![ResetRejected.PNG](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/e84e0958-27c0-4dcd-8aab-b75eedad3b88)

Click RESET.  Status is REJECTED. Cannot Examine from this screen.  RESET button is still available/active. 

Load using the NR Number. Name has APPROVED style. 
![ResetRejected2.PNG](https://images.zenhubusercontent.com/5a7391964b5806bc2bc54a70/c992167a-7c3e-4ad4-939c-bc0a2c730fbf)

**Comment by LJTrent** [comment]
Tested a RESET from REJECTION in dev and it seems to be working properly.
