### ISSUE TITLE
Update Trademark SOLR Query in the SOLR API

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#869]
##### _**Detailed Description**_
Update the query string for the trademarks to push "Registration published" status to the top of the list.  

The current trademark query string is:
 TRADEMARKS: '/solr/trademarks/select?defType=edismax&hl.fl=name&hl.simple.post=%3C/b%3E&hl.simple.pre=%3Cb%3E&'
                    'hl=on&indent=on&mm=75%25&q={name}&qf=name&wt=json&start={start}&rows={rows}&'              'fl=application_number,name,status,description,score**&bq=status:REGISTERED^5.0**{name_copy_clause}'

Change it to=>
&bq=status:"Registration published"^5.0

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
(removed the "bug" tag, since this is a change in requirements)
