### ISSUE TITLE
nro-extractor is updating requests that it shouldn't

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#891]
The nro-extractor is updating requests that have been completed in NameX and overwriting them with the settings from NRO.

**Comment by LJTrent** [comment]
@thorwolpert 

The extractor is not setting the priority_cd =Y.

![image](https://user-images.githubusercontent.com/35615843/45710789-7c248480-bb3c-11e8-8ce5-b771add6eba6.png)
