### ISSUE TITLE
NR# field not displayed for names that appear in the conflicts list

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#899]
##### _**Detailed Description**_
When the name being examined has a conflict, it can be against an active business or against an approved NR that has not been consumed yet. Currently, the Conflicts details pane for approved NRs does not include the NR#

For example: NR 9222965

##### _**Acceptance Criteria**_
Please include the NR# at the top of the fields presented in the Conflicts details pane when an approved NR conflict is highlighted.

![image.png](https://images.zenhubusercontent.com/5a7391bd4b5806bc2bc54a79/8d029718-2a1e-4a82-9200-51389561edfb)
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by JohnamLane** [comment]
I need to postpone testing because I am getting lots of data issues (possible related to aligning the envs?)
The error is: "1) Corp Info Error: Corporation info could not be displayed because it isn't in fdw-registries data."

**Comment by kialj876** [comment]
Yes - so that just means that specific corporation info is not available because our fdw-registries (foreign data wrapper pointing to corporation data) is pointing to data that isn't fully up to date. You should be able to test it against other NR's though. In DEV there will be a lot of missing NR's, but you shouldn't get too many missing corps

**Comment by JohnamLane** [comment]
PASS:
GALAXIUM PENSION FUNDS LIMITED is a known NR conflict in dev.
NR# fields showing at the top of the list in conflicts and history.
@kialj876 Please move to test when you are ready.
