### ISSUE TITLE
Conduct Research Interviews

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#9]
----
----
##### _**Detailed Description**_
Interview examiners to see how they interact with the system as well as the types of issues they encounter and some of their wish list items and pains to be resolved.

##### _**Sprint Goal**_
Required to complete conduct the opportunities workshop and prepare epics, stories and scenarios for development.

##### _**Acceptance Criteria**_
- conduct interviews
- Take notes and record audio/video
- conduct interview with Jill and Kaine regarding Appeals and legislation/policy.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] Acceptance Criteria Defined :one:
- [x] Estimate :two:
- [x] Priority Label :one:
- [x] Task Label :one:
- [x] Assignee :two:
- [x] Sprint Goal (in line with the goal of the sprint) :two:
----
----
#####  _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Detailed Description :one:
- [ ] Rough Inputs :two:
- [ ] Rough Outputs :two:
- [ ] Impacts :two:
- [ ] Users :two::
- [ ] Priority Label :one:
- [ ] Attached Journey Map(s)
- [ ] Attached Relevant Screen Shots from the Existing Application :two:
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] User Story :one:
- [ ] Priority Label :one:
- [ ] Story Label :one:
- [ ] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----
----
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] BDD Pseudo-Code :two:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Scenario Label :one:
- [ ] Assignee :one:
- [ ] Linked Story :one:

----
----

**Comment by JohnamLane** [comment]
Staff interviews - 3 complete, 1 to go
External - 2 complete, 2 to go
