### ISSUE TITLE
Set up authorization in Solr admin app

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#906]
##### _**Detailed Description**_

Due to time constraints, the authorization portion of the solr-admin-app was not completed. The authorization should be set up with two roles:
  - role 1: can edit all synonym fields, and can add and delete synonyms.
  - role 2: can edit the "comments" field for a synonym, but no other fields.

##### _**Acceptance Criteria**_

 - Two roles as described above.
 - An indication of the current logged in user name.
 - A means of logging out.
 - Dev and Production environments remain readonly for all roles.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Done.  Must log in with IDIR.
