### ISSUE TITLE
@ In the Manual Search

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#917]
##### _**Detailed Description**_

When I use Manual Search the @ is not working.  I tested the equivalent of this in the solr admin UI and it is working.  A good example &fq=name_copy: PROVIDENCE is what should be in the query when you supply @PROVIDENCE in the manual search.    It should not stem or use synonyms when the &fq is supplied.  Currently, @PROVIDENCE is returning names with PROVIDENT, PROVIDE.  When I do it in the SOLR Admin UI I only get names with PROVIDENCE which is expected.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
What is the expected query string?
