### ISSUE TITLE
Name Request Details

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#92]
----
##### _**Story Sentence**_ (As a "user type" I want a "goal" so that "benefit".)
As a name examiner, I want to see the details of the name request, so that I can examine it

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] User Story :one:
- [ ] Priority Label :one:
- [x] Story Label :one:
- [x] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----

**Comment by LJTrent** [comment]
Replaced by #116 , #117 , #101
