### ISSUE TITLE
Extractor Not Setting Completed NRs to NAMEX Name State

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#921]
##### _**Detailed Description**_

The extractor is loading COMPLETED requests from NRO as COMPLETED NRs in NAMEX. In NAMEX, a completed NR should be APPROVED, REJECTED or CONDITIONAL.  

When I look in Search at ALL I should not see COMPLETED in NAMEX.  We should see the decision, APPROVED, REJECTED, CONDITIONAL.  eg. NR 0941390 in TEST.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment]
If the Name Request in NRO is in a COMPLETED state, we need to set the Request state in NameX based on what the name_state is. All the other request states should behave the same.
There is a series of tests to exercise the various permutations.

**Comment by LJTrent** [comment]
@thorwolpert  tested asnd it worked.  got a completed, rejected NR from namest that had not been loaded to namex yet and used the postman extractor test to send it to anmex.  Look at it in namex search screen and it was set to rejected as expected.
