### ISSUE TITLE
NRO Cancellation NOT in NAMEX

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#924]
##### _**Detailed Description**_

A draft NRO that is cancelled in NRO does not get updated in NAMEX.  The NRO transaction_id is correct and is in the NAMEX.NAME_transaction table but not the namex_feeder.

eg. in DEV -   NR 7098589

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by thorwolpert** [comment]
Added the 'C' status, in addition to 'D' to the load procedure.
It is in Dev.

**Comment by LJTrent** [comment]
@WalterMoar Can you please deploy this to test in Thor's absence?

**Comment by LJTrent** [comment]
@thorwolpert 
Is  this already in prod?
