### ISSUE TITLE
Add MODIF, CORRT, UPDPR, RESUBMIT Transactions to the NRO Oracle Package

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#925]
##### _**Detailed Description**_
RESUBMIT is alrady there but must be added to the CREATE action in the package not then update action.  Treat it like a NRREQ.  It is basically a new submission for one that was approved but expired.  
  IF row_transaction_type_cd IN ( 'NRREQ'  , 'RESUBMIT') THEN
                        row_action := ACTION_CREATE;

Add the MODIF, CORRT to get any edits made to a  draft submission to NRO over to an existing Draft NR in namex.

Add UPDPR to update the priority from NRO for a draft NR into a draft NR in namex.

~~Add EXTEND to update the expiration_date when an expiration date is EXTENDED in NRO for an approved NR.  This should be included because it will impede our ability to examine it if the date is not updated in NAMEX.~~

**Comment by thorwolpert** [comment]
I'm going to put this into a different ticket:
"Add EXTEND to update the expiration_date when an expiration date is EXTENDED in NRO for an approved NR. This should be included because it will impede our ability to examine it if the date is not updated in NAMEX."

**Comment by thorwolpert** [comment]
I don't see any EXTEND type transactions in the production DB,
SQL> select count(*) from request;
  COUNT(*)
----------
   1460132

SQL> select distinct TRANSACTION_TYPE_CD from transaction order by TRANSACTION_TYPE_CD;
TRANSACTIO
----------
ADMIN
CANCL
CONSUME
CORRT
EXPIR
HISTORICAL
MODIF
NAME_EXAM
NRREQ
RESET
RESUBMIT
UPDPR

**Comment by LJTrent** [comment]
@thorwolpert   yes sorry about that.  EXTEND isnt a transaction.  I believe it ends up being an ADMIN transaction. I guess that means it should be convered and I can test that on Monday since NRO is down right now.  Sorry for being a pest.

**Comment by LJTrent** [comment]
Reminder for Lorna: Test extend in NRO as I think it is an ADMIN transaction that adds a new row to request_instance for the new expiry date that should come across to NAMEX.  We ned to test both sides of this as well as an approved-expired on in NAMEX.

**Comment by LJTrent** [comment]
@thorwolpert 
Modifying a draft NR in NRO is not getting over to NAMEX.  The tranaction is ignored.
MODIF transaction in dev.

NR 2645932,
![image](https://user-images.githubusercontent.com/35615843/45973255-c69d7980-bff2-11e8-9496-50c213516bcd.png)
![image](https://user-images.githubusercontent.com/35615843/45973271-cf8e4b00-bff2-11e8-947b-80ab48d9b931.png)

**Comment by LJTrent** [comment]
@thorwolpert 
NR 2003996  in dev.  Did an Upgrade Priority UPDPR .  I did see it  in the name_transaction table as a P and then it got updated to an I and  no row in the namex_feeder.  
![image](https://user-images.githubusercontent.com/35615843/45974894-960c0e80-bff7-11e8-961a-c3fb8347974a.png)

![image](https://user-images.githubusercontent.com/35615843/45974907-9dcbb300-bff7-11e8-9cc9-a0e568939d7e.png)

**Comment by LJTrent** [comment]
@thorwolpert 
Tested a MODIF on a DRAFT NR,NR 2804551.

It did come across but is missing some of the info.  Missing updates include: applicant first name, address line2 to the applicant address and updated email address. REQUEST_PARTY
Updated  NWPTA SK name but cant see it in the interface so I dont know if it is working.  This would be an update to PARTNER_NAME_SYSTEM. Any updates to NWPTA in NRO ends all rows (both SK, AB) and inserts two new ones even if only one changed, Probably best to grab all with no end_event_id

here is the data in oracle for the missing data:
![image](https://user-images.githubusercontent.com/35615843/46045310-2dde2b00-c0d2-11e8-98e0-3b6b65369c40.png)

old address and new address
![image](https://user-images.githubusercontent.com/35615843/46045378-60882380-c0d2-11e8-92a4-51a11d0d431c.png)

all rows PARTNER_NAME_SYSTEM:
![image](https://user-images.githubusercontent.com/35615843/46045411-7b5a9800-c0d2-11e8-9285-9451fe9fd59f.png)

**Comment by LJTrent** [comment]
@thorwolpert  Retested MODIF and it is still not updating any request_party data.  Still getting the row wrong I believe.  NR 1693924 has two rows in request_party - it is still grabbing he first one in NAMEX.

I checked the view with this NR and it is grabbing the right row just not updating in NAMEX.

![image](https://user-images.githubusercontent.com/35615843/46090625-f9b44a00-c165-11e8-8517-038ac7bfa032.png)

**Comment by LJTrent** [comment]
Update Priority is working.

**Comment by LJTrent** [comment]
@thorwolpert 

MODIF is not updating the request party info and associated address info.
eg. 
NR 0756717.  Looks like it processed according to the namex_feeder but is no reflected in namex.  This is in DEV.

**Comment by LJTrent** [comment]
@thorwolpert @kialj876   This is working can you please promote to test.
