### ISSUE TITLE
Solr: company names view is returning non-unique keys

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#927]
##### _**Detailed Description**_

The solr_dataimport_conflicts_vw view for company names in cdev/ctst/cprd is not returning unique IDs:

SELECT COUNT(id) FROM solr_dataimport_conflicts_vw;
359060

SELECT COUNT(UNIQUE id) FROM solr_dataimport_conflicts_vw;
351501

Solr can only choose one document for a given ID, so the dataimport is non-deterministic.

##### _**Acceptance Criteria**_

The view needs to be corrected to only return the correct data, and it must have unique keys.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar 

Sorry about that.  here is the updated query.  I will leave it to you to get into the db and repo script.

CREATE VIEW NAMEX.SOLR_DATAIMPORT_CONFLICTS_VW
AS SELECT c.corp_num AS ID, corp.corp_nme AS NAME, op.state_typ_cd AS state_type_cd,
           'CORP' AS SOURCE
      FROM corporation c LEFT OUTER JOIN corp_name corp ON corp.corp_num = c.corp_num
           LEFT OUTER JOIN corp_state cs ON cs.corp_num = corp.corp_num
           LEFT OUTER JOIN corp_op_state op ON op.state_typ_cd = cs.state_typ_cd
           LEFT OUTER JOIN corp_type ct ON ct.corp_typ_cd = c.corp_typ_cd
     WHERE corp.end_event_id IS NULL and corp.corp_name_typ_cd  IN ('CO','NB')
       AND cs.end_event_id IS NULL
       AND op.op_state_typ_cd = 'ACT'
AND ct.corp_class IN ('BC', 'SOC', 'OT', 'XPRO')

The counts for dev fusing your queries are: 351,496, 351,496
for test: 375,984,375,984
for prd: 491,927, 491,927

**Comment by WalterMoar** [comment]
Can you slack me the updated GitHub file?

**Comment by LJTrent** [comment]
@WalterMoar  Approved the code review.

**Comment by WalterMoar** [comment]
BTW, this has been deployed to dev, test, and prod and checks out - I think it can be closed.
