### ISSUE TITLE
Restricted Words

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#93]
----
##### _**Story Sentence**_ (As a "user type" I want a "goal" so that "benefit".)
As a name examiner, I want the system to tell me if the name request contains restricted words, so that I can conditionally approve the request. 

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] User Story :one:
- [ ] Priority Label :one:
- [x] Story Label :one:
- [ ] Linked EPIC :two:
- [x] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----

**Comment by LJTrent** [comment]
Replaced by #114
