### ISSUE TITLE
NR with NWPTA NOT Showing in NAMEX

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#931]
##### _**Detailed Description**_
NR 4745075 that has NWPTA both AB, SK defined in NRO is not showing in the NR Details in NAMEX. 
This is not a bad data issue as this was entered by John in last few days from NRO.

Screen snap of NAMEX:
![image.png](https://images.zenhubusercontent.com/5a70ead94b5806bc2bc4f2c4/84e7580f-849f-4b18-870b-242c39ca50b3)

Screen snap of oracle database:
![image.png](https://images.zenhubusercontent.com/5a70ead94b5806bc2bc4f2c4/f3c7de02-142a-4d2c-b0f5-ce4474f7d2db)

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@JohnamLane  Hoping you can do some more testing of this.  I cant seem to replicate the problem but hoping you would do a few in dev starting with nw submission.  What I noticed is that once it was approved, the NWPTA fields stopped displaying and then they came back when it was furnished.  

Can you test a few?

**Comment by JohnamLane** [comment]
@katiemcgoff 
I have retested with fresh data and I am able to reproduce.
NR 2760709 - SK and AB names provided, not showing in dev  namex front end while draft.
In NAMESD there was data in partner_name_system.partner_name_system_id in (363, 364)
I then Quick approved at 10:05, still missing NWPTA #s when I hit edit
Post-furnish: AB/SK #s and expiry dates are showing as expected in namex front end.

NR 8960754 is a fresh name in Dev that you can use to see the same results.

**Comment by LJTrent** [comment]
@JohnamLane  Thanks, John.

**Comment by katiemcgoff** [comment]
@JohnamLane ready for review in dev

**Comment by JohnamLane** [comment]
@katiemcgoff 5582021 still showing the same symptoms in Dev. 
9772448 is another example where the NWPTA #s were requested (not provided) but the fields don't show when you edit.

**Comment by LJTrent** [comment]
@katiemcgoff 

These are ones that I edited the NWPTA fields in NAMEX and they are not showing now in NAMEX. Here are a few: NR 2804551, NR 4745075, NR 9036168.  All of these were edit in NAMEx and donot show any NWPTA fields when loaded into the EXAMINE screen.

**Comment by katiemcgoff** [comment]
@LJTrent @JohnamLane Ready for testing in DEV (as of a few hours ago).

**Comment by JohnamLane** [comment]
PASS, please promote to Test

I completed the following tests:
Names that had NWPTA requested
NR 2745400 - added SK and NUANS numbers
NR 8864803 - added assumed names/numbers
NR 3384269 - added numbered assumed

NWPTA Provided
NR 6545980 - edited existing AB and SK names/numbers
NR 4824615 - edited existing AB and SK assumed names/numbers
NR 2246506 - provided numbered assumed and kept as numbered assumed.

**Comment by JohnamLane** [comment]
@katiemcgoff this passed! Forgot to @ you see above.
