### ISSUE TITLE
Solr: RESET transaction is not being handled

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#934]
##### _**Detailed Description**_

The RESET transaction is not being handled by the Oracle package that decides what to feed to Solr.

##### _**Acceptance Criteria**_

The solr package in Oracle should delete from the "names" and "possible.conflicts" cores when a request is reset.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar Approved. Please deploy to dev.

**Comment by LJTrent** [comment]
@WalterMoar 
RESET NR 5468012.  Al transactions good in namesdb.
Looked at names-transaction and found the transaction but set to Ignore.
![image](https://user-images.githubusercontent.com/35615843/45972157-dbc4d900-bfef-11e8-8b02-33ee0929ec1b.png)

![image](https://user-images.githubusercontent.com/35615843/45972180-e7b09b00-bfef-11e8-8dcf-5b779e826617.png)

stil in the names core:
![image](https://user-images.githubusercontent.com/35615843/45972195-f5feb700-bfef-11e8-9808-f6aed7ecc1c7.png)


still in the possible.conflicts core:
![image](https://user-images.githubusercontent.com/35615843/45972235-0f076800-bff0-11e8-8fe3-2a3f8e706cff.png)


Should be deleted from both.

**Comment by WalterMoar** [comment]
That's strange. Let me take a look.

**Comment by WalterMoar** [comment]
There's an outer loop that also needs to have RESET added to the list of transactions. I wish there was an easy way in PL/SQL to get rid of the redundancy.

**Comment by WalterMoar** [comment]
Deployed to dev.

**Comment by LJTrent** [comment]
@WalterMoar 
The solr feeder ran for a reset but it did not remove it from the names core.

NR 5440518
--
NR 5440518 in Dev
![image](https://user-images.githubusercontent.com/35615843/45981331-754cb480-c009-11e8-8c74-cb3dad087ab8.png)
But it did not remove it from the names core.  If it RESET than it becomes undecided again which means it should be removed.
--

**Comment by LJTrent** [comment]
ok. Looks good.  Promote to test please.

**Comment by WalterMoar** [comment]
Request to promote to test has been submitted to David Roberts, with the hope that we can get test and production done tomorrow.

**Comment by WalterMoar** [comment]
Promoted to test. Cores reloaded in dev and test and should remain in sync with the view counts.
