### ISSUE TITLE
Solr: documentation

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#935]
##### _**Detailed Description**_

We need Solr documentation.

##### _**Acceptance Criteria**_

Documentation including but not limited to:
 - Description on the customizations (solr-jdbc, and its requirements)
 - Description of installing Solr as a standalone app on the desktop
 - Installation steps for OpenShift and/or Minishift install of Solr
 - Flow diagram for Solr feeder
 - Description of the trademarks loader
 - Operations guide for Solr, solr-feeder, solr-admin-app
    - How is solr set-up?  Pods, deployments, imports, feeders ... In openshift, oracle...
    - How do tell if solr is running?
    - How do investigate conflict issues or name history issues, trademarks issues?

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar  Reviewed and ready for Merge.
