### ISSUE TITLE
Implement Cancel - front and back end

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#937]
After discussion in team, we are adding Cancel functionality to Namex.

Implementation notes: 
- follows similar model as RESET:
  - button on screen
  - force user to enter comment
  - patch with status (check actual Namex "cancelled" status)
  - make sure status gets sent back to NRO - similar to NRO service to set to H

**Comment by katiemcgoff** [comment]
Per John, an NR can be cancelled as long as it is not yet consumed or expired.

**Comment by katiemcgoff** [comment]
Oracle cancel status in request_state is 'C'.

**Comment by katiemcgoff** [comment]
@LJTrent @JohnamLane This is ready for testing in DEV

**Comment by katiemcgoff** [comment]
@LJTrent @JohnamLane  NOT ready for testing yet. Need an Oracle database permission set up first.

**Comment by katiemcgoff** [comment]
Waiting on permissions needed for request_state (update, insert) and change permission (update?) on request_state_seq.

**Comment by LJTrent** [comment]
@katiemcgoff 
Cancel shoudl not be available on a completed NR.  If it has already been approved or rejected. It must be RESET before it can be canceled.  Therefore the Cancel Request button must be disabled if it is a APPROVED, REJECTED or CONDITIONAL request in NAMEX.

**Comment by JohnamLane** [comment]
@katiemcgoff @LJTrent I had provided the advice that staff can cancel any NR that is not expired or consumed, but this is based on how NRO works today. The Reset feature changes this. Sorry about that.
