### ISSUE TITLE
Allow edit of Expiration Date

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#938]
All user to edit expiration date after closed, eliminating need to edit expiry date in NRO - and therefore eliminating need to send back that data from oracle to namex.

Implementation notes:
- follow similar date entry/validation/conversion as nwpta dates
- is editable only after furnished, ie: only after it exists
- is required if is being edited, since we cannot blank out expiration date
- should already be picked up in Edit NR oracle functionality (Oracle Services > change_nr()) so probably no changes needed for Oracle

**Comment by LJTrent** [comment]
@katiemcgoff  Working.  Please promote to test.  One thing to note is that the comment will no go back to NRO because we are not making a decision.  We have to deal with all of these when we detach the comments.
