### ISSUE TITLE
Examination Recipe

### ISSUE THREAD

**Issue by juliainkster** [bcgov/name-examination#94]
##### _**Story Sentence**_ (As a "user type" I want a "goal" so that "benefit".)
As a names examiner, I want to see a recipe of steps  that were used to make the decision so that I can approve and reject in a consistent manner.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [x] User Story :one:
- [x] Priority Label :one:
- [x] Story Label :one:
- [x] Linked EPIC :two:
- [ ] Linked Scenarios :two:
- [ ] Inputs(Data) :one:
- [ ] Outputs(Data) :one:
- [ ] Attached Sketch/Mock-up
- [ ] User Research Test Results
----

**Comment by LJTrent** [comment]
Replaced by #187
