### ISSUE TITLE
Solr - split compound words using dictionary (solr.DictionaryCompoundWordTokenFilterFactory)

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#940]
##### _**Detailed Description**_
Clients often submit names that contain compound words as the distinctive. For example: "SOULFIT VICTORIA". Currently, Solr will try and find the exact term SOULFIT, which will not locate results with either SOUL or FIT.

The Dictionary Compound Word Token Filter can locate and split such terms out.
(https://lucene.apache.org/solr/guide/6_6/language-analysis.html#LanguageAnalysis-DictionaryCompoundWordTokenFilter)

This filter uses a dictionary of English words. If any of the dictionary words are found anywhere within any of the search terms then the dictionary word is added as a search term.

I have uploaded a reasonable English dictionary to SharePoint since GitHub doesn't seem to like the file.
https://sbc.gov.bc.ca/bcregistries/Names Examination/dictionary.txt

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Not being done.
