### ISSUE TITLE
Solr: fix Oracle package return values on raise

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#946]
##### _**Detailed Description**_

The Oracle feeder packages have functions that generate JSON. If there is an exception raised in these functions, they are not providing a return value, which causes the caller to fail.

##### _**Acceptance Criteria**_

Functions should behave properly and not cause the caller to fail. Probably re-raise the exception after logging, or maybe return a null value? (less desirable).

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar  Not sure why this is assigned to me or how I could test it?  Any suggestions?

**Comment by WalterMoar** [comment]
I think it is basically self-tested because the error that was repeatedly occurring in the test environment stopped as soon as the package was updated.
