### ISSUE TITLE
How do  we Know if one of the other systems is down?

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#949]
##### _**Detailed Description**_

How do we know if one of the feeder systems are down such as COLIN  or NRO?

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by perkinss** [comment]
Hmm... this is a question, and not a story or task.  How can we determine if it's been completed?

**Comment by LJTrent** [comment]
There are multiple tickets.
