### ISSUE TITLE
Solr: in Oracle escape quotation marks for JSON

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#959]
##### _**Detailed Description**_

The data for the Solr feeder is not properly handling quotation marks in names. If not done, the JSON is malformed and rejected by solr-feeder.

##### _**Acceptance Criteria**_

Names containing quotation marks should be fed into Solr. The quotation marks must be retained.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar  ready to merge and deploy to dev.

**Comment by WalterMoar** [comment]
Deployed to dev.

**Comment by LJTrent** [comment]
@WalterMoar  Ready for test.
