### ISSUE TITLE
Solr: queries using @ do not handle it in unexpected positions

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#960]
##### _**Detailed Description**_

Update the Solr API to properly handle searches such as "this is@ nonsense" or "this is @ nonsense". Solr searches with @ trailing a word or @ by itself should ignore the character.

##### _**Acceptance Criteria**_

Write tests for the above, and correct the code to pass the tests.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
@WalterMoar  There is nothing to merge as it is closed so I assume you already merged it into dev.

**Comment by WalterMoar** [comment]
Merged by Thor; it was also pushed to test by someone at 3:39.

**Comment by LJTrent** [comment]
@WalterMoar   tested this in dev. The @ sign is working with quotation marks in words as well.  eg. @GEORGE's -AUTO -PARTS@PLUS LLP.

However when I add additional special characters with the @ sign at the beginning I get a 500 error. 
For example,
This works: +!TSARLIP^! AUTO-PARTS@PLUS LLP

But this does not: @!TSARLIP^! AUTO-PARTS@PLUS LLP.
