### ISSUE TITLE
Inconsistent Date TimeZone in Namex

### ISSUE THREAD

**Issue by katiemcgoff** [bcgov/name-examination#965]
Steps to reproduce:
- as customer, submit NR in NRO (public)
- note time. For example, 2 pm on Oct 2 in Victoria.

Expected result:
- in Namex, submission date is Oct 2 at 2 pm.

Actual result:
- in Namex, submission date is Oct 2 at 7 am.

**Comment by perkinss** [comment]
Looks like a Time zone/ daylight savings time issue.

**Comment by katiemcgoff** [comment]
Something to remember - the servers (ie: python) are in GMT. Database is in GMT. During development, the "server" (developer machine) is in Pacific timezone. This leads to confusion.

**Comment by LJTrent** [comment]
Replaced by a ticket on the entity board.
