### ISSUE TITLE
Edited a Co-Op Does Not Require a Jurisdiction

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#969]
##### _**Detailed Description**_

When you edit a Cooperative - Amalgamation/Incorporation Request Type does not require a jurisdiction.  Currently the UI has it as a required field.  Only Cooperative - Extraprovincial ... requires a jurisdiction. In fact I just checked all the Cooperative - Extra provincial ... request types and the jursidiction doesnt show so I think the logic needs to be switched.

![image.png](https://images.zenhubusercontent.com/5a70ead94b5806bc2bc4f2c4/52478096-97df-4037-b80a-b1d5d6e2eae8)
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
@LJTrent ready for testing in DEV environment.

**Comment by LJTrent** [comment]
@katiemcgoff  Ready to promote to TEST.
