### ISSUE TITLE
400 error when retrieved NR has a space suffix

### ISSUE THREAD

**Issue by WalterMoar** [bcgov/name-examination#972]
##### _**Detailed Description**_

In the web front end I copied an NR number out of Outlook and pasted it into the *NR Number* box at the top of the application. The copy out of Outlook had a space after the number, such as "1234567 ". When I clicked the *Quick Approve* button, I received an error with the message _Request failed with status code 400_.

##### _**Acceptance Criteria**_

A trailing space in the NR search box should not prevent approving a name.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
@LJTrent ready for review DEV

**Comment by JohnamLane** [comment]
@LJTrent @katiemcgoff Pass, I have tested this in dev.

**Comment by ericminio** [comment]
Secured by test in https://github.com/bcgov/name-examination/pull/1022

**Comment by ericminio** [comment]
I believe it is still failing if you have only spaces in the search box.
We have this captured in a skipped test in https://github.com/bcgov/name-examination/pull/1026

**Comment by JohnamLane** [comment]
@katiemcgoff Tested in test - ready for prod.
