### ISSUE TITLE
Add a company's previous names to the corporate name conflict details pane

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#973]
##### _**Detailed Description**_
When a name conflict is returned by Solr search, examiners can click it to see the complete details pulled from Corporate Online (CPRD). One of the fields brought over is the corporate name.

When choosing a conflict among similar names, examiners must choose the oldest company for the conflict; this is determined using the incorporation date which is provided.

as an enhancement, examiners would like to see the corporations historical names in the case that it has changed its name. This would prevent them from having to search the company in COLIN which is what they will still need to do in some cases.

**Comment by juliainkster** [comment]
NEs would like to see name changes/historical names and dates for a conflict.  See attached COLIN report for details they look for.  This could be in the conflicting name "Compare" details.

[https://app.zenhub.com/files/118046288/25db22cf-b0b9-485f-93f8-a1e65b8d2798/download](https://app.zenhub.com/files/118046288/25db22cf-b0b9-485f-93f8-a1e65b8d2798/download)

**Comment by LJTrent** [comment]
Not being done.  Look at LEAR.
