### ISSUE TITLE
Correct Missing Fields for Request Type

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#975]
##### _**Detailed Description**_

Limited Partnership and Limited Partnership extra pro have the jusridiction flag on the wrong set. please switch.  You should also probably check: Limited Liability Partnership  Limited Liability Partnership extrapro... 

*The following request types are missing the Jurisdiction field:*
Cooperative - Extraprovincial Reinstatement
Cooperative - Extraprovincial Change of Name
Cooperative - Extraprovincial Registration
Limited Liability Partnership - Extraprovincial Change of Name
Limited Liability Partnership - Extraprovincial Registration
Extraprovincial Limited Partnership
Limited Partnership - Extraprovincial Change of Name
Society - Extraprovincial Non-Share Corporation Assumed Name
Society - Extraprovincial Non-Share Corporation Change Assumed Name
Society - Extraprovincial
Society - Extraprovincial Restoration
Society - Extraprovincial Change of Name
Society - Extraprovincial Restoration
Society - Extraprovincial Change of Name
ULC - Extraprovincial Registration
ULC - Extraprovincial Reinstatement
Change of Name of Extrapro Unlimited Liability Company

*These requests are missing the Related Corp num:*
ULC - BC to ULC Conversion
ULC - Change of Name
Limited Liability Partnership - Change of Name

*This one is missing the Previous NR:*
Society - Extraprovincial Non-Share Corporation Assumed Name

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by JohnamLane** [comment]
@katiemcgoff 
These two name types are still missing Jurisdiction:
- Change of Name of Extrapro Unlimited Liability Company
- ULC - Extraprovincial Reinstatement

ULC - Extraprovincial Reinstatement
--

**Comment by katiemcgoff** [comment]
@JohnamLane lastest changes ready to review in DEV:

> These two name types are still missing Jurisdiction:
>
>- Change of Name of Extrapro Unlimited Liability Company
>- ULC - Extraprovincial Reinstatement

**Comment by JohnamLane** [comment]
Testing still in progress:
Society Extraprovincial still shows the Previous NR field

**Comment by katiemcgoff** [comment]
@JohnamLane Are you saying that this - "Society - Extraprovincial" that is code "XSO" - should not see Previous NR field?

**Comment by katiemcgoff** [comment]
@JohnamLane Here's the spreadsheet that governs the rules around showing jurisdiction, previous NR, corp num, and nwpta. Can you please review against whatever spreadsheet you have and make sure that this is correct? Some of the recent issues have been that this spreadsheet is missing some types entirely, so please consider that as well. Also, the descriptions are often not the same but the code - the first column - is what matters.

https://github.com/bcgov/name-examination/blob/master/client/static/ui_dropdowns/request_type_rules.csv

**Comment by katiemcgoff** [comment]
@katiemcgoff to update spreadsheet from John.

**Comment by katiemcgoff** [comment]
@JohnamLane ready for review in DEV.

Also fixed a bug that was inserting <nwpta> in Additional Info. That was not the intention, it is actually to be ignored.

**Comment by JohnamLane** [comment]
@katiemcgoff Ready to move to test.

**Comment by katiemcgoff** [comment]
@JohnamLane Ready for review in TEST. If I don't hear from you by about 6 pm today (Tuesday) I'll just push it to production along with the few other changes getting deployed before examiners start using this tomorrow.

**Comment by LJTrent** [comment]
@katiemcgoff  Sorry. I put this one in the backlog to get the CCR added for NWPTA.  Hoeflly this is the last one.

**Comment by katiemcgoff** [comment]
@LJTrent @JohnamLane Per discussion/analysis yesterday, we're going to just remove any restriction on nwpta based on request type. That way if NRO lets the user enter/request nwpta, we will show it, whether that's conceptual but or not. That's what I will implement now and send to Lorna for review.

**Comment by katiemcgoff** [comment]
@LJTrent ready for your review in DEV. Basically you'd need to find an NR with NWPTA and then change type to anything (such as BC change of name) and still see nwpta info - no hiding it based on request type.

**Comment by katiemcgoff** [comment]
@JohnamLane Sorry I should have updated - this was expedited on Friday and is now in production, to enable examiners (Alan specifically) to enter requested nwpta info.
