### ISSUE TITLE
Handle Upload Consent in NRO by the Client

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#976]
##### _**Detailed Description**_
One of the last admin functions to be moved from NRO to Namex is the handling of the consent received flag.
When a name is conditionally approved, support staff must go to NRO and flip a 'consent received' flag after the client has provided their consent documents.

Currently, namex has the concept of a name being conditionally approved, but it is missing the flag to indicate that consent was received.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Should be part of the new NRO.

**Comment by JohnamLane** [comment]
This ticket it so show that consent has been received in Namex once it has been entered in NRO, so it won't go away with the NRO re-write. It could change a lot if the whole consent process changes, though.

**Comment by LJTrent** [comment]
@JohnamLane There is another ticket for showing it in Namex.  That is why I closed this one.  I am cleaning up all namex/NRo tickets.
