### ISSUE TITLE
Correct Request Types that Require Corp Num

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#978]
##### _**Detailed Description**_

There are a few request types that do not show the corp num field.  I have a list in an excel spreadsheet.
*These requests are missing the Related Corp num:*
ULC - BC to ULC Conversion
ULC - Change of Name
Limited Liability Partnership - Change of Name

*This one is missing the Previous NR:*
Society - Extraprovincial Non-Share Corporation Assumed Name
##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by JohnamLane** [comment]
@katiemcgoff Pass. I tested in test and all of the cases mentioned above look good. Thanks!
