### ISSUE TITLE
Load SOLR Cores in Prod

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#979]
##### _**Detailed Description**_

Load the solr cores in prod and turn in the feeders.

##### _**Sprint Goal**_
Verify they are staying sync with the views and the feeders are working properly.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by WalterMoar** [comment]
Cores loaded.
