### ISSUE TITLE
Conflicts remain on approved name choice

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#991]
##### _**Detailed Description**_
If there are any results in the Conflicts recipe step, then the first one is highlighted by default. When the examiner moves to the Decision screen, this conflict is pre-selected.  This conflict remains even if they approve the name choice.

Stripping the conflict and it's text from the "message to requestor" won't be possible if they have edited the message already.

Options:
- Make a more explicit "Add conflict" button on the examine screen
- Prevent the first conflict by being chosen by default (yet somehow show it's details in the pane?)

**Comment by juliainkster** [comment]
The new design eliminates the decisions screen.

**Comment by LJTrent** [comment]
The system already wipes out the conflict when the outcome is approved and doesn't send the conflict back to NRO.    Once the full decision text is displayed on a completed NR there of course will be no conflict.
