### ISSUE TITLE
Condition - restricted word chosen in one decision shows in next name (after get next)

### ISSUE THREAD

**Issue by JohnamLane** [bcgov/name-examination#993]
##### _**Detailed Description**_
Steps to reproduce:
- Examine a name with a restricted word in it (e.g. trustee)
- Highlight the restricted word in the Condition recipe step, then click Decision
- Conditionally approve the name, the click Get next
- Click the Decision button - the old restricted word will still be selected even if there are no results in the Condition list

Lorna, assigning to you for prioritization

**Comment by perkinss** [comment]
Well this is fun... if you don't manually clear it, it will stay there with every getNext.
