### ISSUE TITLE
Investigate Effort for a Few UI Changes

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#995]
##### _**Detailed Description**_

There are a few things that the examiners could benefit from that require a technical review to determine the scope and effort of the ask.  For these items please consult with John and Julia to determine details but in a nutshell please investigate the following items:

1)  Increasing the overall font size.  Personally I need to bump it up to about 110% to be readable.
2) Add Hot keys to all buttons.
3) Change tab order so that from manual search you tab to the first item in the conflict list if there are conflicts.
4) Reduce the size of the submission info box that is displayed.

##### _**Acceptance Criteria**_
Technical tickets with an evaluation of the work required, design, any refactoring and new tests required.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by katiemcgoff** [comment]
Upon discussion (Kaine, John, Susan, Katie):

1. font size - can be done. LOE 1/2 day. #1000 

1a)  Related changes (will log separately) re. examination boxes (conflict/history):
- make cols 3 and 4 narrower
- make arrows narrower
- conflicts and history list wider
- font inside lists bigger
- vertical padding of options in lists bigger (start w. 5px and review w. John)

2. hot keys - can implement for all keys, will start the work but wait on exact keys requested from John/Kaine

3. tab order - yes, very quick change but implications to other tab orders. Will get done asap so can be reviewed next week (week of Oct 15)

4. decrease NR header - wait on mockup from John; we discussed nwpta chg and maybe priority chg.

@LJTrent What did you have in mind for front-end tests? I think we are about to have Jest tests running, is that what you meant?

**Comment by LJTrent** [comment]
@katiemcgoff  Front-end test for now shoudl include  I believe JEST  and may include any unit testing we agree upon.  We will need @ericminio  input regarding front-end unit testing.

**Comment by katiemcgoff** [comment]
Investigation done, all UI improvements implemented and moving through pipelines.
