### ISSUE TITLE
Update Solr Names Conflict View

### ISSUE THREAD

**Issue by LJTrent** [bcgov/name-examination#998]
##### _**Detailed Description**_
The SOLR_DATAIMPORT_CONFLICTS_VW in names needs to be updated to allow SYST events for EXPIR transaction, TRUNC of the expiration_date to handle ones that expire that day while the EXPIR job that updates the transaction table does not urn until 3:40 am and as well handle request that have been Cancelled but have an approved name.  We only want approved names for COMPLETED requests.

##### _**Acceptance Criteria**_
Implement view in all environments, dev, test, prod and reload possible conflicts core.

##### _**Definition of Done**_ (:one:-Mandatory to add to the Backlog, :two:-Mandatory to add to the Sprint Backlog)
- [ ] Acceptance Criteria Defined :one:
- [ ] Estimate :two:
- [ ] Priority Label :one:
- [ ] Task Label :one:
- [ ] Assignee :two:
- [ ] Sprint Goal (in line with the goal of the sprint) :two:
----
----

**Comment by LJTrent** [comment]
Walter updated in dev and kept the old ones as _vw2.  The new one is missing some sections of the query and needs to be updated.

**Comment by WalterMoar** [comment]
The view SOLR_DATAIMPORT_CONFLICTS_VW in NAMESD.NAMEX has been updated with the changes.
