### ISSUE TITLE
Local storage must be moved to Session storage

### ISSUE THREAD

**Issue by thorwolpert** [bcgov/name-examination#999]
#### **Task**
In the Vue app, local info such as JWT must not be in local storage so if needed should be in session storage

##### _**Detailed Description**_
change where variables are stored from Local to Session storage.

**Comment by JohnamLane** [comment]
@katiemcgoff Confirmed in Test - Under Session Storage I see KEYCLOAK_REFRESH and KEYCLOAK_TOKEN and they aren't showing under local storage. Ready for production.
